// AUTO-GENERATED by the official-fight generator (a dev tool, kept local) from
// an in-game FrenMits sheet
// (Doomtrain (EX), territory 1308). The Actions[] arrays ARE the Auto-planned mit for each column; times
// are seconds from the pull. Review the mit assignments before shipping - they are
// the planner's, not hand-authored. Regenerate by re-running the tool.
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class DoomtrainData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(13, "P1", "Dead Man's Overdraught", 0, new[]{"Reprisal", "Party Mit", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "Feint", "", "Party Mit", "Addle"}),
        new(21, "P1", "Dead Man's Express", 0xB266, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(23, "P1", "Plasma Beam", 0xB268, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(26, "P1", "Hyperexplosive Plasma", 0, new[]{"Party Mit", "Reprisal", "Liturgy of the Bell + Temperance", "Neutral Sect + Celestial Opposition", "Seraphism + Expedient", "Holos + Philosophia", "", "Feint", "", ""}, 1, false),
        new(32, "P1", "Dead Man's Overdraught", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(40, "P1", "Dead Man's Windpipe", 0xB26D, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(43, "P1", "Dead Man's Blastpipe", 0xB26F, new[]{"", "", "Asylum", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(45, "P1", "Plasma", 0, new[]{"", "", "", "", "Seraph", "", "", "", "", ""}, 1, false),
        new(52, "P1", "Unlimited Express", 0xB237, new[]{"", "", "", "", "Fey Illumination", "", "", "", "", ""}, 1, false),
        new(65, "P1", "Dead Man's Overdraught", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(70, "P1", "Turret Crossing", 0xB23C, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(80, "P1", "Dead Man's Express", 0xB266, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "", "", "", ""}),
        new(82, "P1", "Plasma Beam", 0xB268, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 1, true),
        new(85, "P1", "Plasma", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(91, "P1", "Dead Man's Overdraught", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(98, "P1", "Lightning Burst", 0xB25C, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(108, "P1", "Dead Man's Windpipe", 0xB26D, new[]{"", "", "", "Celestial Opposition", "", "Panhaima", "Feint", "", "Party Mit", "Addle"}),
        new(111, "P1", "Dead Man's Blastpipe", 0xB26F, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(113, "P1", "Hyperexplosive Plasma", 0, new[]{"", "Reprisal", "Asylum", "", "Sacred Soil", "", "", "", "", ""}, 1, false),
        new(120, "P1", "Unlimited Express", 0xB237, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(136, "P1", "Lightning Burst", 0xB25C, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(149, "P1", "Runaway Train", 0xB246, new[]{"Reprisal", "Party Mit", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "", "Feint", "", ""}),
        new(176, "P1", "Aetherosote", 0, new[]{"Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(176, "P1", "Aetherial Ray", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(192, "P1", "Aetherosote", 0, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 2, true),
        new(192, "P1", "Aetherial Ray", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(204, "P1", "Aetherochar", 0, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(204, "P1", "Aetherial Ray", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(231, "P1", "Runaway Train", 0, new[]{"Party Mit + Reprisal + Short Mit", "Party Mit + Short Mit", "Temperance + Asylum", "Neutral Sect + Earthly Star", "Sacred Soil + Seraphism", "Kerachole + Philosophia", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(250, "P1", "Shockwave", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(260, "P1", "Lightning Burst", 0xB25C, new[]{"Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(268, "P1", "Derailment Siege", 0xB250, new[]{"", "Reprisal", "Plenary Indulgence", "Collective Unconscious + Celestial Opposition", "Expedient + Seraph + Fey Illumination", "Holos + Physis II + Kerachole", "", "Feint", "", ""}, 2, false),
        new(271, "P1", "Derailment Siege", 0xB251, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(277, "P1", "Derail", 0xB28F, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(292, "P1", "Third Rail", 0, new[]{"", "", "", "", "Sacred Soil", "", "", "", "", ""}),
        new(301, "P1", "Headlight", 0xB27A, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(305, "P1", "Thunderous Breath", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(310, "P1", "Arcane Revelation", 0xB9A7, new[]{"", "", "", "", "", "Kerachole", "", "", "", ""}),
        new(322, "P1", "Hail of Thunder", 0, new[]{"Party Mit + Reprisal", "Party Mit + Short Mit", "Asylum", "Macrocosmos + Earthly Star", "Whispering Dawn + Sacred Soil", "Panhaima", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(322, "P1", "Hyperconductive Plasma", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(333, "P1", "Hail of Thunder", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(333, "P1", "Hyperconductive Plasma", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(350, "P1", "Hail of Thunder", 0, new[]{"Short Mit", "Reprisal + Short Mit", "Plenary Indulgence", "Collective Unconscious + Celestial Opposition", "", "Kerachole + Physis II", "", "", "", ""}, 2, false),
        new(350, "P1", "Hyperconductive Plasma", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(362, "P1", "Thunderous Breath", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(372, "P1", "Third Rail", 0, new[]{"", "", "", "", "Sacred Soil", "", "", "", "", ""}),
        new(381, "P1", "Derailment Siege", 0, new[]{"Buddy Mit", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(385, "P1", "Derailment Siege", 0, new[]{"Reprisal", "Short Mit", "Liturgy of the Bell + Temperance", "Neutral Sect + Earthly Star", "Whispering Dawn", "Kerachole", "", "Feint", "", ""}, 3, false),
        new(392, "P1", "Derail", 0xB599, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(409, "P1", "Psychokinesis", 0, new[]{"", "", "", "", "Sacred Soil", "", "", "", "", ""}),
        new(410, "P1", "Plummet", 0, new[]{"", "Reprisal", "Plenary Indulgence", "Collective Unconscious + Celestial Opposition", "Expedient + Seraph + Fey Illumination", "Holos + Physis II", "", "", "", ""}, 2, false),
        new(415, "P1", "Third Rail", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(424, "P1", "Psychokinesis", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(425, "P1", "Plummet", 0, new[]{"Party Mit", "Party Mit", "Asylum", "", "Seraphism", "Philosophia + Kerachole", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(431, "P1", "Lightning Burst", 0xB25C, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 2, true),
        new(440, "P1", "Psychokinesis", 0, new[]{"", "", "", "", "Sacred Soil", "", "", "", "", ""}),
        new(441, "P1", "Plummet", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(446, "P1", "Third Rail", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(457, "P1", "Derailment Siege", 0xB285, new[]{"Buddy Mit", "Short Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(463, "P1", "Derailment Siege", 0xB288, new[]{"Reprisal + Rampart", "", "", "Earthly Star", "Whispering Dawn", "Panhaima + Kerachole", "", "", "", ""}, 3, false),
        new(469, "P1", "Derail", 0xB28F, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(483, "P1", "Dead Man's Overdraught", 0, new[]{"", "Reprisal", "Plenary Indulgence", "Collective Unconscious + Celestial Opposition", "Sacred Soil", "Physis II", "", "Feint", "", ""}),
        new(488, "P1", "Turret Crossing", 0xB23C, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(500, "P1", "Headlight", 0xB27A, new[]{"", "", "", "", "", "Kerachole", "", "", "", ""}),
        new(504, "P1", "Thunderous Breath", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many rows
            // ask for it. Keyed on the ACTION, not the row's cast: two mechanics
            // do land on one second, and a player told to press different things
            // for each is being told to press both.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    // The board's severity marks (! !! !!!) and tank-buster icon come off
    // FightProfile.CustomRows - Hurt/Buster live nowhere else - so a built-in has
    // to hand them over the same way SyncPoints and BossAnchors are handed over,
    // or an official sheet silently loses every grade the source sheet had.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        return SyncAnchors.Build(
            Timeline.Select(e => (e.Sync, (float)e.Time, e.Phase, e.Mechanic)));
    }

    public static List<BossAnchor> BossAnchors() => new();
}
