// AUTO-GENERATED by tools/gen_official_fight.py from an in-game FrenMits sheet
// (Enuo (EX), territory 1362). The Actions[] arrays ARE the Auto-planned mit for each column; times
// are seconds from the pull. Review the mit assignments before shipping - they are
// the planner's, not hand-authored. Regenerate by re-running the tool.
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class EnuoData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(15, "P1", "Meteorain", 0xC381, new[]{"Party Mit + Reprisal + Short Mit", "Party Mit + Short Mit", "Temperance + Asylum + Plenary Indulgence", "Neutral Sect + Earthly Star + Collective Unconscious", "Seraphism + Expedient + Seraph", "Philosophia + Holos + Physis II", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(30, "P1", "Naught Grows", 0xC337, new[]{"", "Reprisal", "Liturgy of the Bell", "Macrocosmos + Celestial Opposition", "Whispering Dawn + Sacred Soil", "Panhaima + Kerachole", "", "Feint", "", ""}, 1, false),
        new(32, "P1", "Return to Nothing", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(39, "P1", "Naught Wakes", 0xC335, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(45, "P1", "Meltdown", 0xC378, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(51, "P1", "Meltdown", 0xC379, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(58, "P1", "Dense Emptiness", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(68, "P1", "Naught Grows", 0xC337, new[]{"", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(70, "P1", "Great Return to Nothing", 0, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(85, "P1", "Gaze of the Void", 0xC352, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(89, "P1", "Gaze of the Void", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(95, "P1", "Violent Burst", 0, new[]{"Invulnerability", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(95, "P1", "Burst", 0, new[]{"", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious + Celestial Opposition", "Fey Illumination + Whispering Dawn + Sacred Soil", "Physis II + Kerachole", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(101, "P1", "Violent Burst", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(102, "P1", "Burst", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(111, "P1", "Vacuum", 0xC34A, new[]{"Reprisal", "Party Mit", "Asylum", "", "", "", "", "", "", ""}),
        new(117, "P1", "Silent Torrent", 0xC350, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(123, "P1", "Airy Emptiness", 0, new[]{"Party Mit", "Reprisal", "", "", "", "", "", "Feint", "", ""}, 1, false),
        new(134, "P1", "Deep Freeze", 0xC37B, new[]{"Buddy Mit", "Short Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(142, "P1", "Meteorain", 0xC381, new[]{"", "", "Temperance", "Neutral Sect", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(156, "P1", "All for Naught", 0xC35A, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(175, "P1", "Looming Emptiness", 0xC35B, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Panhaima + Kerachole", "", "", "", ""}),
        new(184, "P1", "Voidal Turbulence", 0, new[]{"", "", "", "Celestial Opposition", "Expedient + Seraph", "Holos + Physis II", "", "", "", ""}, 2, false),
        new(185, "P1", "Empty Shadow", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(192, "P1", "Demon Eye", 0xC366, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(212, "P1", "Voidal Turbulence", 0, new[]{"Party Mit", "Party Mit + Reprisal", "Asylum", "Macrocosmos", "Seraphism + Sacred Soil", "Philosophia + Kerachole", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(213, "P1", "Empty Shadow", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(217, "P1", "Curse of the Flesh", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(255, "P1", "Nothingness", 0, new[]{"Buddy Mit", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(258, "P1", "Nothingness", 0, new[]{"", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "", "Feint", "", ""}),
        new(277, "P1", "Lightless World", 0xC36D, new[]{"Reprisal", "", "Temperance", "Neutral Sect + Celestial Opposition", "Fey Illumination", "", "", "", "", ""}, 2, false),
        new(292, "P1", "Almagest", 0xC334, new[]{"", "Reprisal", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(305, "P1", "Naught Grows", 0xC338, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(307, "P1", "Great Return to Nothing", 0, new[]{"Party Mit", "Party Mit", "Asylum", "", "Expedient + Seraph", "Panhaima + Holos", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(314, "P1", "Naught Wakes", 0xC335, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(322, "P1", "Passage of Naught", 0, new[]{"", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "", "", "", ""}),
        new(334, "P1", "Passage of Naught", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(339, "P1", "Shrouded Holy", 0xC37D, new[]{"Reprisal", "", "", "Celestial Opposition", "", "", "", "", "", ""}, 1, false),
        new(354, "P1", "Naught Grows", 0xC338, new[]{"Buddy Mit", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(356, "P1", "Great Return to Nothing", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, true),
        new(366, "P1", "Dimension Zero", 0xC37F, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(379, "P1", "Vacuum", 0xC34A, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(386, "P1", "Meltdown", 0xC378, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(386, "P1", "Silent Torrent", 0xC350, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(391, "P1", "Meltdown", 0xC379, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(405, "P1", "Gaze of the Void", 0xC352, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(409, "P1", "Gaze of the Void", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(414, "P1", "Burst", 0, new[]{"", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(415, "P1", "Violent Burst", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(416, "P1", "Burst", 0, new[]{"Party Mit + Reprisal", "Party Mit", "Liturgy of the Bell + Temperance + Asylum", "Macrocosmos + Neutral Sect + Earthly Star", "Seraphism + Fey Illumination + Whispering Dawn", "Philosophia + Physis II", "", "Feint", "Party Mit", "Addle"}, 3, false),
        new(420, "P1", "Violent Burst", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(423, "P1", "Burst", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(438, "P1", "Almagest", 0xC334, new[]{"Rampart + Short Mit", "Reprisal + Short Mit", "Plenary Indulgence", "Collective Unconscious + Celestial Opposition", "Expedient + Seraph", "Holos + Kerachole", "Feint", "", "", ""}, 2, false),
        new(448, "P1", "Naught Wakes", 0xC335, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(457, "P1", "Naught Hunts", 0xC348, new[]{"", "", "", "", "Sacred Soil", "", "", "", "", ""}),
        new(458, "P1", "Passage of Naught", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(484, "P1", "Airy Emptiness", 0, new[]{"Reprisal", "", "", "Earthly Star", "Whispering Dawn", "Panhaima + Physis II", "", "", "", ""}, 1, false),
        new(496, "P1", "Naught Hunts", 0xC348, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(497, "P1", "Passage of Naught", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(523, "P1", "Dense Emptiness", 0, new[]{"Party Mit", "Party Mit + Reprisal", "Asylum + Plenary Indulgence", "Collective Unconscious + Celestial Opposition", "Sacred Soil", "Kerachole", "", "Feint", "Party Mit", "Addle"}, 1, false),
        new(534, "P1", "Dimension Zero", 0xC37F, new[]{"Short Mit", "Short Mit", "", "", "", "", "Feint", "", "", ""}, 2, false),
        new(538, "P1", "Dimension Zero", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(549, "P1", "Almagest", 0xC334, new[]{"Reprisal", "", "Temperance", "Neutral Sect + Earthly Star", "Fey Illumination + Whispering Dawn", "Physis II + Kerachole", "", "", "", ""}, 1, false),
        new(561, "P1", "Naught Grows", 0xC338, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(563, "P1", "Great Return to Nothing", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(570, "P1", "Naught Wakes", 0xC335, new[]{"", "", "", "", "Sacred Soil", "Holos", "", "", "", ""}),
        new(579, "P1", "Passage of Naught", 0, new[]{"", "", "", "", "", "Kerachole", "", "", "", ""}),
        new(590, "P1", "Passage of Naught", 0, new[]{"", "Reprisal", "Plenary Indulgence", "Collective Unconscious + Celestial Opposition", "Expedient", "", "", "", "", ""}),
        new(595, "P1", "Deep Freeze", 0xC37B, new[]{"", "", "", "", "Seraph", "", "", "", "", ""}, 1, false),
        new(609, "P1", "Naught Grows", 0xC338, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(611, "P1", "Great Return to Nothing", 0, new[]{"", "", "Liturgy of the Bell", "Earthly Star", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "", "Feint", "Party Mit", "Addle"}, 1, false),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many rows
            // ask for it. Keyed on the ACTION, not the row's cast: two mechanics
            // do land on one second, and a player told to press different things
            // for each is being told to press both.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    // The board's severity marks (! !! !!!) and tank-buster icon come off
    // FightProfile.CustomRows - Hurt/Buster live nowhere else - so a built-in has
    // to hand them over the same way SyncPoints and BossAnchors are handed over,
    // or an official sheet silently loses every grade the source sheet had.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        var points = new List<SyncPoint>();
        var phaseSeen = new HashSet<string>();
        var prevTime = float.NegativeInfinity;
        foreach (var e in Timeline.Where(e => e.Sync != 0).OrderBy(e => e.Time))
        {
            var isPhaseAnchor = phaseSeen.Add(e.Phase) || (e.Time - prevTime) > 90f;
            points.Add(new SyncPoint { Ability = e.Sync, Time = e.Time, IsPhase = isPhaseAnchor, Label = $"{e.Phase} {e.Mechanic}" });
            prevTime = e.Time;
        }
        return points;
    }

    public static List<BossAnchor> BossAnchors() => new();
}
