// AUTO-GENERATED by the official-fight generator (a dev tool, kept local) from
// an in-game FrenMits sheet (M10S - Red Hot / Deep Blue, territory 1323).
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class M10sData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(15, "P1", "Hot Impact", 0xB5B6, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(30, "P1", "Flame Floater", 0xB5BA, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 1, true),
        new(34, "P1", "Flame Floater", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(37, "P1", "Flame Floater", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(41, "P1", "Flame Floater", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(53, "P1", "Alley-Oop Inferno", 0xB5C0, new[]{"Party Mit + Reprisal", "Party Mit + Short Mit", "Temperance + Asylum + Plenary Indulgence", "Neutral Sect + Earthly Star + Collective Unconscious", "Seraphism + Expedient + Seraph", "Philosophia + Holos + Physis II", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(63, "P1", "Cutback Blaze", 0xB5C9, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(69, "P1", "Pyrotation", 0xB5C2, new[]{"", "Reprisal", "", "Celestial Opposition", "Fey Illumination + Whispering Dawn", "Kerachole", "", "Feint", "", ""}, 1, false),
        new(74, "P1", "Pyrotation", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(83, "P1", "Divers' Dare", 0xB5B8, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(98, "P1", "Sick Swell", 0xB5CB, new[]{"", "", "", "", "Sacred Soil", "", "", "", "", ""}),
        new(107, "P1", "Sickest Take-Off", 0xB5CD, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(116, "P1", "Sickest Take-Off", 0xB5CE, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "", "Kerachole + Physis II", "", "", "", ""}),
        new(116, "P1", "Sick Swell", 0xB5CC, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(119, "P1", "Awesome Splash", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(126, "P1", "Alley-Oop Double-Dip", 0xB5DD, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(129, "P1", "Alley-Oop Double-Dip", 0, new[]{"Buddy Mit", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(137, "P1", "Deep Impact", 0xB5B7, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, true),
        new(145, "P1", "Divers' Dare", 0xB5B9, new[]{"Party Mit", "Party Mit + Reprisal", "Asylum", "Celestial Opposition", "Sacred Soil + Whispering Dawn", "", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(162, "P1", "Xtreme Spectacular", 0xB5D9, new[]{"", "", "", "", "", "Kerachole", "", "", "", ""}),
        new(170, "P1", "Xtreme Spectacular", 0xB5A4, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(174, "P1", "Xtreme Spectacular", 0, new[]{"Reprisal", "", "Plenary Indulgence", "", "", "", "", "", "", ""}, 1, false),
        new(196, "P1", "Insane Air", 0xB897, new[]{"", "", "Liturgy of the Bell + Temperance", "Neutral Sect + Earthly Star", "Sacred Soil + Expedient", "Kerachole + Holos", "", "Feint", "", ""}, 1, false),
        new(199, "P1", "Plunging Snap", 0, new[]{"", "", "", "Macrocosmos + Collective Unconscious + Celestial Opposition", "Seraph + Fey Illumination", "Panhaima + Physis II", "", "", "", ""}, 2, false),
        new(199, "P1", "Blasting Snap", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(203, "P1", "Insane Air", 0xB899, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(206, "P1", "Vertical Plunge", 0, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(206, "P1", "Re-Entry Blast", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(210, "P1", "Insane Air", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(213, "P1", "Plunging Snap", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(213, "P1", "Blasting Snap", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(218, "P1", "Insane Air", 0, new[]{"", "Reprisal", "", "", "Whispering Dawn", "", "", "", "", ""}, 1, false),
        new(221, "P1", "Re-Entry Plunge", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(221, "P1", "Vertical Blast", 0, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 2, true),
        new(230, "P1", "Divers' Dare", 0xB5B8, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 2, false),
        new(246, "P1", "Firesnaking", 0xB381, new[]{"Party Mit + Reprisal", "Party Mit", "Asylum + Plenary Indulgence", "", "Seraphism", "Philosophia", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(246, "P1", "Watersnaking", 0xB382, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(258, "P1", "Alley-Oop Inferno", 0xB5C0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(258, "P1", "Reverse Alley-Oop", 0xB5E0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(264, "P1", "Sick Swell", 0xB5CB, new[]{"", "", "", "Earthly Star", "Sacred Soil", "Kerachole + Physis II", "", "", "", ""}),
        new(270, "P1", "Hot Impact", 0xB580, new[]{"Invulnerability", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(276, "P1", "Deep Varial", 0xB891, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(281, "P1", "Alley-Oop Inferno", 0xB5C1, new[]{"Short Mit", "Reprisal", "", "Collective Unconscious + Celestial Opposition", "Whispering Dawn", "", "", "Feint", "", ""}, 2, false),
        new(281, "P1", "Awesome Splash", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(290, "P1", "Hot Aerial", 0xB5C4, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(293, "P1", "Sickest Take-Off", 0xB5CD, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(294, "P1", "Hot Aerial", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(298, "P1", "Hot Aerial", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(303, "P1", "Sickest Take-Off", 0xB5CE, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(303, "P1", "Sick Swell", 0xB5CC, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(305, "P1", "Awesome Slab", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(308, "P1", "Cutback Blaze", 0xB5C9, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2),
        new(315, "P1", "Deep Impact", 0xB5B7, new[]{"", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(322, "P1", "Divers' Dare", 0xB5B8, new[]{"Reprisal", "Rampart", "Temperance + Plenary Indulgence", "Neutral Sect", "Expedient + Seraph", "Holos", "", "", "", ""}, 2, false),
        new(335, "P1", "Deep Aerial", 0xB5E3, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(348, "P1", "Xtreme Wave", 0xB5C5, new[]{"Party Mit", "Party Mit + Reprisal", "Asylum", "Earthly Star + Collective Unconscious", "Fey Illumination + Whispering Dawn", "Kerachole + Physis II", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(350, "P1", "Scathing Steam", 0xADC7, new[]{"", "Short Mit", "", "Celestial Opposition", "Sacred Soil", "", "", "", "", ""}, 2, false),
        new(356, "P1", "Xtreme Wave", 0xB5C8, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(358, "P1", "Scathing Steam", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(365, "P1", "Xtreme Wave", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(367, "P1", "Scathing Steam", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(373, "P1", "Xtreme Wave", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(375, "P1", "Scathing Steam", 0xADC7, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(382, "P1", "Xtreme Wave", 0xB5C7, new[]{"Reprisal", "", "Plenary Indulgence", "", "Sacred Soil", "Kerachole", "", "Feint", "", ""}, 1, false),
        new(384, "P1", "Scathing Steam", 0, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 2, false),
        new(390, "P1", "Xtreme Wave", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(393, "P1", "Scathing Steam", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(401, "P1", "Divers' Dare", 0xB5B8, new[]{"Rampart", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(413, "P1", "Sick Swell", 0xB5CB, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(417, "P1", "Flame Floater", 0xB5D4, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(425, "P1", "Alley-Oop Inferno", 0xB5C0, new[]{"Short Mit", "Reprisal + Rampart + Short Mit", "", "Earthly Star + Collective Unconscious + Celestial Opposition", "Whispering Dawn", "Physis II", "", "", "", ""}, 2, false),
        new(431, "P1", "Alley-Oop Double-Dip", 0xB5DD, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(434, "P1", "Alley-Oop Double-Dip", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(438, "P1", "Sickest Take-Off", 0xB5CD, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(438, "P1", "Freaky Pyrotation", 0xB596, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(447, "P1", "Sickest Take-Off", 0xB5CE, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(447, "P1", "Sick Swell", 0xB5CC, new[]{"Party Mit + Reprisal", "Party Mit", "Liturgy of the Bell + Temperance", "Macrocosmos + Neutral Sect", "", "", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(450, "P1", "Awesome Slab", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(454, "P1", "Divers' Dare", 0xB5B9, new[]{"Short Mit", "Short Mit", "Asylum + Plenary Indulgence", "", "Seraphism + Expedient + Seraph", "Philosophia + Holos", "", "", "", ""}, 2, false),
        new(470, "P1", "Xtreme Firesnaking", 0xB5AE, new[]{"", "", "", "", "Fey Illumination", "Panhaima", "", "Feint", "", ""}, 3, false),
        new(470, "P1", "Xtreme Watersnaking", 0xB5AF, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many
            // rows ask for it.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        return SyncAnchors.Build(
            Timeline.Select(e => (e.Sync, (float)e.Time, e.Phase, e.Mechanic)));
    }

    public static List<BossAnchor> BossAnchors() => new();
}
