// AUTO-GENERATED by the official-fight generator (a dev tool, kept local) from
// an in-game FrenMits sheet
// (M11S - The Tyrant, territory 1325). The Actions[] arrays ARE the Auto-planned mit for each column; times
// are seconds from the pull. Review the mit assignments before shipping - they are
// the planner's, not hand-authored. Regenerate by re-running the tool.
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class M11sData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(11, "P1", "Crown of Arcadia", 0xB406, new[]{"Party Mit + Reprisal", "Party Mit", "Temperance + Asylum", "Neutral Sect + Earthly Star", "Seraphism + Expedient", "Kerachole + Physis II", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(19, "P1", "Raw Steel Trophy", 0xB422, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(25, "P1", "Raw Steel", 0, new[]{"Invulnerability", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(26, "P1", "Impact", 0, new[]{"", "Reprisal", "Plenary Indulgence", "Collective Unconscious + Celestial Opposition", "Sacred Soil + Whispering Dawn", "Holos", "", "Feint", "", ""}, 1, false),
        new(40, "P1", "Trophy Weapons", 0xB416, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(49, "P1", "Assault Evolved", 0xB417, new[]{"", "", "", "", "Seraph", "Panhaima + Kerachole", "", "", "", ""}),
        new(51, "P1", "Sweeping Victory", 0, new[]{"", "", "", "", "Fey Illumination", "Philosophia", "", "", "", ""}, 1, false),
        new(52, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(57, "P1", "Sharp Taste", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(57, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(62, "P1", "Heavy Weight", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(62, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(74, "P1", "Trophy Weapons", 0xB416, new[]{"Reprisal", "", "", "Earthly Star", "Sacred Soil", "Physis II", "", "", "", ""}),
        new(81, "P1", "Void Stardust", 0xB412, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(85, "P1", "Cometite", 0xB413, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(89, "P1", "Cometite", 0, new[]{"", "Reprisal", "Plenary Indulgence", "Collective Unconscious + Celestial Opposition", "Whispering Dawn", "Kerachole", "", "", "", ""}, 1, false),
        new(91, "P1", "Comet", 0xB414, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(94, "P1", "Assault Evolved", 0xB417, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(96, "P1", "Heavy Weight", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(96, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(101, "P1", "Sweeping Victory", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(102, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(107, "P1", "Sharp Taste", 0, new[]{"Party Mit", "Party Mit", "Asylum", "", "Sacred Soil", "", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(107, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(112, "P1", "Cometite", 0xB413, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(116, "P1", "Cometite", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(118, "P1", "Crushing Comet", 0xB415, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(124, "P1", "Crown of Arcadia", 0xB406, new[]{"", "", "", "", "", "Kerachole", "", "Feint", "", ""}, 1, false),
        new(137, "P1", "Dance of Domination Trophy", 0xB7BB, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(143, "P1", "Dance of Domination", 0xB41F, new[]{"Reprisal", "", "Temperance", "Neutral Sect + Earthly Star", "Expedient + Sacred Soil", "Physis II", "", "", "", ""}, 1, false),
        new(147, "P1", "Dance of Domination", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(152, "P1", "Eye of the Hurricane", 0xB424, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(152, "P1", "Explosion", 0xB420, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(158, "P1", "Raw Steel Trophy", 0xB423, new[]{"", "Reprisal", "Plenary Indulgence", "Collective Unconscious + Celestial Opposition", "Whispering Dawn", "Kerachole", "", "", "", ""}),
        new(166, "P1", "Raw Steel", 0, new[]{"Buddy Mit", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(166, "P1", "Heavy Hitter", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(181, "P1", "Charybdistopia", 0xB425, new[]{"", "", "", "", "Sacred Soil", "Holos", "", "", "", ""}),
        new(187, "P1", "Ultimate Trophy Weapons", 0xB7ED, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(194, "P1", "Assault Apex", 0xB7EE, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(197, "P1", "Heavy Weight", 0, new[]{"Party Mit", "Party Mit", "Liturgy of the Bell + Asylum", "Macrocosmos", "Seraphism + Seraph", "Panhaima + Kerachole", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(197, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(202, "P1", "Sweeping Victory", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(202, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(207, "P1", "Sharp Taste", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(207, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(212, "P1", "Sharp Taste", 0, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Fey Illumination + Whispering Dawn", "Physis II", "", "", "", ""}, 1, false),
        new(212, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(217, "P1", "Sweeping Victory", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(217, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(222, "P1", "Heavy Weight", 0, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(222, "P1", "Assault Evolved", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(229, "P1", "Powerful Gust", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(230, "P1", "Immortal Reign", 0xB428, new[]{"", "", "", "Collective Unconscious + Celestial Opposition", "Sacred Soil", "Kerachole", "", "Feint", "", ""}),
        new(240, "P1", "One and Only", 0xB429, new[]{"", "Reprisal", "", "", "", "Philosophia", "", "", "", ""}, 1, false),
        new(243, "P1", "One and Only", 0xB42A, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(255, "P1", "Great Wall of Fire", 0xB42B, new[]{"Buddy Mit", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(258, "P1", "Great Wall of Fire", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(259, "P1", "Explosion", 0xB42E, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(262, "P1", "Explosion", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(268, "P1", "Orbital Omen", 0xB432, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(277, "P1", "Fire and Fury", 0xB42F, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Whispering Dawn", "Physis II", "", "", "", ""}),
        new(278, "P1", "Orbital Omen", 0xB433, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(295, "P1", "Meteorain", 0xB434, new[]{"Party Mit", "Party Mit", "Asylum", "Collective Unconscious + Celestial Opposition", "Sacred Soil", "Kerachole", "Feint", "", "Party Mit", "Addle"}),
        new(302, "P1", "Fearsome Fireball", 0xB439, new[]{"", "Reprisal", "Temperance", "Neutral Sect", "Expedient", "Holos", "", "", "", ""}, 1, false),
        new(304, "P1", "Cosmic Kiss", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(312, "P1", "Foregone Fatality", 0, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(312, "P1", "Fearsome Fireball", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(314, "P1", "Cosmic Kiss", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(316, "P1", "Explosion", 0xB438, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(322, "P1", "Foregone Fatality", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(322, "P1", "Fearsome Fireball", 0xB439, new[]{"", "", "", "", "Seraph + Sacred Soil", "Panhaima + Kerachole", "", "Feint", "", ""}, 1, false),
        new(324, "P1", "Cosmic Kiss", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(326, "P1", "Explosion", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(332, "P1", "Foregone Fatality", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(332, "P1", "Fearsome Fireball", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(336, "P1", "Explosion", 0xB438, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(345, "P1", "Triple Tyrannhilation", 0xB43C, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Whispering Dawn", "Physis II", "", "", "", ""}),
        new(363, "P1", "Flatliner", 0xB43F, new[]{"", "Reprisal", "", "Collective Unconscious", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(379, "P1", "Majestic Meteor", 0xB440, new[]{"Party Mit", "Party Mit", "Asylum", "Celestial Opposition", "Fey Illumination", "", "Feint", "", "Party Mit", "Addle"}),
        new(392, "P1", "Explosion", 0xB444, new[]{"", "", "", "", "Seraphism + Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(403, "P1", "Majestic Meteor", 0xB441, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(406, "P1", "Fire Breath", 0xB446, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(407, "P1", "Majestic Meteowrath", 0, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Whispering Dawn", "Physis II", "", "", "", ""}, 1, false),
        new(407, "P1", "Majestic Meteor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(424, "P1", "Explosion", 0xB444, new[]{"Buddy Mit", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(435, "P1", "Majestic Meteor", 0xB441, new[]{"", "", "Temperance", "Collective Unconscious + Celestial Opposition", "Sacred Soil", "Kerachole", "", "Feint", "", ""}),
        new(438, "P1", "Fire Breath", 0xB446, new[]{"", "Reprisal", "", "Neutral Sect", "Expedient", "Philosophia + Holos", "", "", "", ""}, 1, false),
        new(439, "P1", "Majestic Meteowrath", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(439, "P1", "Majestic Meteor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(448, "P1", "Massive Meteor", 0xB448, new[]{"", "", "", "", "Seraph", "", "", "", "", ""}, 2, false),
        new(454, "P1", "Massive Meteor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(462, "P1", "Explosion", 0xB444, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(463, "P1", "Arcadion Avalanche", 0xB44E, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(473, "P1", "Arcadion Avalanche", 0xB44F, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(483, "P1", "Crown of Arcadia", 0xB406, new[]{"Reprisal", "Party Mit", "Plenary Indulgence", "Earthly Star", "Whispering Dawn", "Physis II", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(494, "P1", "Great Wall of Fire", 0xB42B, new[]{"Invulnerability", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(498, "P1", "Great Wall of Fire", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(498, "P1", "Explosion", 0xB42E, new[]{"Party Mit", "", "Asylum", "Collective Unconscious + Celestial Opposition", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(502, "P1", "Explosion", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(508, "P1", "Orbital Omen", 0xB432, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(517, "P1", "Fire and Fury", 0xB42F, new[]{"", "Reprisal", "", "", "Fey Illumination", "", "", "Feint", "", ""}),
        new(517, "P1", "Orbital Omen", 0xB433, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(522, "P1", "Orbital Omen", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(526, "P1", "Crown of Arcadia", 0xB406, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(538, "P1", "Ecliptic Stampede", 0xB452, new[]{"Reprisal", "", "Liturgy of the Bell + Plenary Indulgence", "Earthly Star", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "", "", "", ""}),
        new(545, "P1", "Mammoth Meteor", 0xB453, new[]{"", "", "Temperance", "Macrocosmos", "", "Panhaima", "", "", "", ""}, 1, false),
        new(545, "P1", "Atomic Impact", 0, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(548, "P1", "Majestic Meteor", 0xB455, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(548, "P1", "Atomic Impact", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(550, "P1", "Majestic Meteor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(551, "P1", "Atomic Impact", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(552, "P1", "Majestic Meteor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(554, "P1", "Atomic Impact", 0, new[]{"Rampart + Short Mit", "", "", "", "", "", "", "", "", ""}, 2, true),
        new(556, "P1", "Majestic Meteor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(557, "P1", "Atomic Impact", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(558, "P1", "Majestic Meteor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(560, "P1", "Atomic Impact", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, true),
        new(561, "P1", "Cosmic Kiss", 0xB456, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 3, true),
        new(561, "P1", "Weighty Impact", 0xB457, new[]{"", "", "", "Collective Unconscious + Celestial Opposition", "Expedient", "Holos", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(571, "P1", "Majestic Meteowrath", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(574, "P1", "Two-Way Fireball", 0xB7BD, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(584, "P1", "Crown of Arcadia", 0xB406, new[]{"", "Reprisal", "", "Neutral Sect", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(596, "P1", "Heartbreak Kick", 0, new[]{"Buddy Mit", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(601, "P1", "Heartbreak Kick", 0, new[]{"", "Party Mit", "Plenary Indulgence", "Earthly Star", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "", "", "", ""}, 1, false),
        new(605, "P1", "Heartbreak Kick", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(615, "P1", "Heartbreak Kick", 0, new[]{"", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(621, "P1", "Heartbreak Kick", 0, new[]{"Buddy Mit", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(625, "P1", "Heartbreak Kick", 0, new[]{"", "", "Asylum", "Collective Unconscious + Celestial Opposition", "Seraph", "Philosophia", "", "Feint", "", ""}, 1, false),
        new(637, "P1", "Heartbreak Kick", 0, new[]{"Party Mit + Reprisal", "", "", "", "Seraphism + Fey Illumination", "Kerachole", "", "", "", ""}, 2, false),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many rows
            // ask for it. Keyed on the ACTION, not the row's cast: two mechanics
            // do land on one second, and a player told to press different things
            // for each is being told to press both.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    // The board's severity marks (! !! !!!) and tank-buster icon come off
    // FightProfile.CustomRows - Hurt/Buster live nowhere else - so a built-in has
    // to hand them over the same way SyncPoints and BossAnchors are handed over,
    // or an official sheet silently loses every grade the source sheet had.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        var points = new List<SyncPoint>();
        var phaseSeen = new HashSet<string>();
        var prevTime = float.NegativeInfinity;
        foreach (var e in Timeline.Where(e => e.Sync != 0).OrderBy(e => e.Time))
        {
            var isPhaseAnchor = phaseSeen.Add(e.Phase) || (e.Time - prevTime) > 90f;
            points.Add(new SyncPoint { Ability = e.Sync, Time = e.Time, IsPhase = isPhaseAnchor, Label = $"{e.Phase} {e.Mechanic}" });
            prevTime = e.Time;
        }
        return points;
    }

    public static List<BossAnchor> BossAnchors() => new();
}
