// AUTO-GENERATED by the official-fight generator (a dev tool, kept local) from
// an in-game FrenMits sheet
// (M1S - Black Cat, territory 1226). The Actions[] arrays ARE the Auto-planned mit for each column; times
// are seconds from the pull. Review the mit assignments before shipping - they are
// the planner's, not hand-authored. Regenerate by re-running the tool.
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class M1sData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(14, "P1", "Quadruple Crossing", 0x943C, new[]{"Party Mit + Reprisal", "Party Mit", "Liturgy of the Bell + Temperance + Asylum", "Macrocosmos + Neutral Sect + Celestial Opposition", "Seraphism + Expedient + Seraph", "Panhaima + Philosophia + Holos", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(20, "P1", "Quadruple Crossing", 0x943D, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(33, "P1", "Biscuit Maker", 0x9495, new[]{"Invulnerability", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(50, "P1", "Nine Lives", 0x9461, new[]{"", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Fey Illumination", "Kerachole + Physis II", "", "Feint", "", ""}, 1, false),
        new(58, "P1", "One-Two Paw", 0x9439, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(62, "P1", "One-Two Paw", 0x943A, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(66, "P1", "Soulshade", 0x9462, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(80, "P1", "Nine Lives", 0x9461, new[]{"Reprisal", "", "", "", "Whispering Dawn", "", "", "", "", ""}, 1, false),
        new(83, "P1", "One-Two Paw", 0x9469, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(88, "P1", "Quadruple Swipe", 0x945D, new[]{"Rampart + Short Mit", "Rampart", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 2, false),
        new(94, "P1", "Soulshade", 0x9462, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(101, "P1", "Leaping Quadruple Crossing", 0x9457, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(106, "P1", "Leaping Quadruple Crossing", 0, new[]{"Party Mit", "Party Mit + Short Mit", "Asylum", "", "", "", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(111, "P1", "Leaping Quadruple Crossing", 0x945A, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(113, "P1", "Quadruple Swipe", 0x9480, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(123, "P1", "Bloody Scratch", 0, new[]{"Short Mit", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil", "Physis II + Kerachole", "", "", "", ""}, 3, false),
        new(146, "P1", "Mouser", 0x9441, new[]{"Reprisal", "Short Mit", "Temperance", "Neutral Sect + Celestial Opposition", "Expedient + Seraph", "Holos", "", "Feint", "", ""}, 2, false),
        new(168, "P1", "Copycat", 0x9445, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(178, "P1", "Elevate and Eviscerate", 0, new[]{"", "Reprisal", "Plenary Indulgence", "", "Fey Illumination + Whispering Dawn", "Panhaima + Kerachole", "", "", "", ""}, 1, false),
        new(180, "P1", "Shockwave", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(181, "P1", "Impact", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(188, "P1", "Elevate and Eviscerate", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(192, "P1", "Shockwave", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(194, "P1", "Impact", 0, new[]{"", "", "", "Earthly Star + Collective Unconscious", "Sacred Soil", "Physis II", "", "", "", ""}, 1, false),
        new(203, "P1", "Shockwave", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(205, "P1", "Elevate and Eviscerate", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(209, "P1", "Impact", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(214, "P1", "Shockwave", 0, new[]{"Reprisal", "Party Mit", "Asylum", "", "", "Kerachole", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(225, "P1", "Biscuit Maker", 0x9495, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(229, "P1", "Grimalkin Gale", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(236, "P1", "Shockwave", 0x944B, new[]{"Party Mit", "", "", "", "Sacred Soil", "", "", "Feint", "", ""}),
        new(241, "P1", "Grimalkin Gale", 0x9B84, new[]{"", "Reprisal", "Plenary Indulgence", "", "Whispering Dawn + Seraphism", "Philosophia", "", "", "", ""}, 2, false),
        new(257, "P1", "Nine Lives", 0x9461, new[]{"", "", "", "Earthly Star", "Sacred Soil", "Kerachole + Physis II", "", "", "", ""}, 1, false),
        new(265, "P1", "Leaping One-Two Paw", 0, new[]{"Short Mit", "Short Mit", "Temperance", "Collective Unconscious", "", "Holos", "", "", "", ""}, 2, false),
        new(273, "P1", "Soulshade", 0x9462, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 1, true),
        new(278, "P1", "Nine Lives", 0x9461, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(286, "P1", "Leaping Quadruple Crossing", 0, new[]{"Reprisal", "", "", "", "", "", "", "", "", ""}),
        new(292, "P1", "Leaping Quadruple Crossing", 0x9459, new[]{"Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(300, "P1", "Soulshade", 0x9462, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(327, "P1", "Leaping One-Two Paw", 0x9478, new[]{"Party Mit + Rampart + Short Mit", "Party Mit + Reprisal + Short Mit", "Liturgy of the Bell + Asylum + Plenary Indulgence", "Neutral Sect + Celestial Opposition + Earthly Star", "Expedient + Seraph + Fey Illumination", "Physis II + Kerachole", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(338, "P1", "Nailchipper", 0, new[]{"", "", "", "", "Whispering Dawn", "", "", "", "", ""}),
        new(339, "P1", "Leaping Quadruple Crossing", 0, new[]{"", "", "", "", "Sacred Soil", "", "", "", "", ""}, 2, false),
        new(341, "P1", "Tempestuous Tear", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(345, "P1", "Leaping Quadruple Crossing", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(348, "P1", "Nailchipper", 0, new[]{"Reprisal", "", "", "Collective Unconscious", "", "", "", "Feint", "", ""}, 2, false),
        new(372, "P1", "Bloody Scratch", 0, new[]{"Short Mit", "Rampart + Short Mit", "", "Macrocosmos", "Sacred Soil", "Panhaima + Kerachole", "", "", "", ""}, 3, false),
        new(395, "P1", "Mouser", 0x9441, new[]{"", "Reprisal", "Temperance + Plenary Indulgence", "Earthly Star", "Whispering Dawn", "Holos + Physis II", "", "", "", ""}, 2, false),
        new(416, "P1", "Copycat", 0x9445, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(426, "P1", "Elevate and Eviscerate", 0, new[]{"Party Mit + Reprisal", "Party Mit", "Asylum", "Collective Unconscious", "Seraphism + Sacred Soil", "Philosophia + Kerachole", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(429, "P1", "Shockwave", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(429, "P1", "Overshadow", 0x9497, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many rows
            // ask for it. Keyed on the ACTION, not the row's cast: two mechanics
            // do land on one second, and a player told to press different things
            // for each is being told to press both.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    // The board's severity marks (! !! !!!) and tank-buster icon come off
    // FightProfile.CustomRows - Hurt/Buster live nowhere else - so a built-in has
    // to hand them over the same way SyncPoints and BossAnchors are handed over,
    // or an official sheet silently loses every grade the source sheet had.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        var points = new List<SyncPoint>();
        var phaseSeen = new HashSet<string>();
        var prevTime = float.NegativeInfinity;
        foreach (var e in Timeline.Where(e => e.Sync != 0).OrderBy(e => e.Time))
        {
            var isPhaseAnchor = phaseSeen.Add(e.Phase) || (e.Time - prevTime) > 90f;
            points.Add(new SyncPoint { Ability = e.Sync, Time = e.Time, IsPhase = isPhaseAnchor, Label = $"{e.Phase} {e.Mechanic}" });
            prevTime = e.Time;
        }
        return points;
    }

    public static List<BossAnchor> BossAnchors()
    {
        var list = new List<BossAnchor>();
        BossNames.Add(list, "Black Cat", 5.6f, "Black Cat");
        return list;
    }
}
