// AUTO-GENERATED by the official-fight generator (a dev tool, kept local) from
// an in-game FrenMits sheet
// (M2S - Honey B. Lovely, territory 1228). The Actions[] arrays ARE the Auto-planned mit for each column; times
// are seconds from the pull. Review the mit assignments before shipping - they are
// the planner's, not hand-authored. Regenerate by re-running the tool.
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class M2sData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(11, "P1", "Call Me Honey", 0x9183, new[]{"Party Mit + Reprisal + Short Mit", "Party Mit + Short Mit", "Liturgy of the Bell + Temperance + Asylum", "Macrocosmos + Neutral Sect + Celestial Opposition", "Seraphism + Expedient + Seraph", "Philosophia + Holos + Panhaima", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(18, "P1", "Splash of Venom", 0x9184, new[]{"Rampart", "", "", "", "", "", "", "", "", ""}, 1),
        new(34, "P1", "Splash of Venom", 0, new[]{"", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Fey Illumination + Whispering Dawn + Sacred Soil", "Physis II + Kerachole", "", "Feint", "", ""}, 3, false),
        new(38, "P1", "Tempting Twist", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(38, "P1", "Honey Beeline", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(40, "P1", "Drop of Venom", 0x9185, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1),
        new(53, "P1", "Drop of Venom", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(60, "P1", "Stinging Slash", 0x919B, new[]{"Invulnerability", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(73, "P1", "Honey B. Live: 1st Beat", 0x9C24, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(80, "P1", "Honey B. Live: 1st Beat", 0, new[]{"Reprisal + Short Mit", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 3, false),
        new(88, "P1", "Outerstage Combo", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(89, "P1", "Laceration", 0, new[]{"", "", "", "", "", "", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(95, "P1", "Laceration", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(103, "P1", "Love Me Tender", 0x919F, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(113, "P1", "Fracture", 0x91A3, new[]{"Party Mit + Short Mit", "Party Mit + Reprisal + Short Mit", "Asylum + Plenary Indulgence", "Earthly Star + Collective Unconscious", "Whispering Dawn + Sacred Soil", "Physis II + Kerachole", "", "", "", ""}, 2, false),
        new(121, "P1", "Fracture", 0x91A3, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(125, "P1", "Fracture", 0x91A3, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(133, "P1", "Fracture", 0x91A3, new[]{"", "", "Temperance", "Neutral Sect + Celestial Opposition", "Expedient + Seraph", "Holos", "", "Feint", "", ""}, 2, false),
        new(136, "P1", "Loveseeker", 0x9B7D, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(150, "P1", "Love Me Tender", 0x919F, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(159, "P1", "Heartsick", 0, new[]{"Reprisal", "", "", "", "Fey Illumination", "", "", "", "", ""}, 1, false),
        new(169, "P1", "Centerstage Combo", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(170, "P1", "Laceration", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(176, "P1", "Laceration", 0, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(187, "P1", "Honey B. Finale", 0x918F, new[]{"", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Whispering Dawn", "Panhaima + Physis II", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(201, "P1", "Killer Sting", 0x919C, new[]{"Buddy Mit", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(210, "P1", "Alarm Pheromones", 0x917D, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(248, "P1", "Honey B. Live: 2nd Beat", 0x9C25, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(254, "P1", "Honey B. Live: 2nd Beat", 0, new[]{"Party Mit + Reprisal + Rampart + Short Mit", "Party Mit + Rampart + Short Mit", "Liturgy of the Bell + Temperance + Asylum", "Macrocosmos + Neutral Sect + Celestial Opposition", "Seraphism + Expedient + Seraph", "Philosophia + Holos + Physis II", "", "Feint", "", ""}, 3, false),
        new(262, "P1", "Drop of Love", 0x9B09, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(272, "P1", "Love Me Tender", 0x919F, new[]{"", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(276, "P1", "Heart-Struck", 0x91A7, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(280, "P1", "Heartsick", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(286, "P1", "Heartsore", 0, new[]{"Short Mit", "Short Mit", "", "", "Fey Illumination", "", "", "", "", ""}, 2, false),
        new(288, "P1", "Fracture", 0x91A3, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(297, "P1", "Tempting Twist", 0x9B0D, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(297, "P1", "Honey Beeline", 0x9B0C, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(302, "P1", "Drop of Love", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(311, "P1", "Honey B. Finale", 0x918F, new[]{"", "", "", "", "Sacred Soil", "Panhaima + Kerachole", "", "", "", ""}, 3, false),
        new(329, "P1", "Drop of Venom", 0x9185, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1),
        new(334, "P1", "Alarm Pheromones", 0x917D, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(342, "P1", "Poison Sting", 0x9194, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(347, "P1", "Poison Sting", 0, new[]{"Party Mit + Reprisal + Rampart", "Party Mit + Rampart + Short Mit", "Asylum + Plenary Indulgence", "Earthly Star + Collective Unconscious", "Whispering Dawn", "Physis II", "", "Feint", "", ""}, 2, false),
        new(352, "P1", "Poison Sting", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(357, "P1", "Poison Sting", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(367, "P1", "Bee Sting", 0x91A8, new[]{"Short Mit", "Reprisal", "", "", "", "", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(389, "P1", "Honey Beeline", 0, new[]{"", "Short Mit", "Temperance", "Neutral Sect + Celestial Opposition", "Sacred Soil + Expedient", "Kerachole + Holos", "", "", "", ""}, 2, false),
        new(394, "P1", "Drop of Venom", 0, new[]{"Short Mit", "", "", "", "Seraph", "", "", "", "", ""}, 3, false),
        new(407, "P1", "Honey B. Live: 3rd Beat", 0x9C26, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(414, "P1", "Honey B. Live: 3rd Beat", 0, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Fey Illumination + Whispering Dawn", "Physis II", "", "", "", ""}, 3, false),
        new(429, "P1", "Laceration", 0, new[]{"", "Reprisal", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(435, "P1", "Laceration", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(437, "P1", "Centerstage Combo", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(438, "P1", "Outerstage Combo", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(440, "P1", "Big Burst", 0, new[]{"Party Mit + Rampart + Short Mit", "Party Mit + Rampart + Short Mit", "Liturgy of the Bell + Asylum", "Macrocosmos", "Seraphism", "Panhaima + Philosophia", "", "Feint", "", ""}, 2, false),
        new(443, "P1", "Fracture", 0x91A3, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(448, "P1", "Laceration", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(455, "P1", "Laceration", 0, new[]{"", "", "", "", "", "", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(460, "P1", "Big Burst", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(463, "P1", "Fracture", 0x91A3, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(485, "P1", "Honey B. Finale", 0x918F, new[]{"Reprisal + Short Mit", "Short Mit", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Whispering Dawn + Sacred Soil", "Physis II + Kerachole", "", "", "", ""}, 3, false),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many rows
            // ask for it. Keyed on the ACTION, not the row's cast: two mechanics
            // do land on one second, and a player told to press different things
            // for each is being told to press both.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    // The board's severity marks (! !! !!!) and tank-buster icon come off
    // FightProfile.CustomRows - Hurt/Buster live nowhere else - so a built-in has
    // to hand them over the same way SyncPoints and BossAnchors are handed over,
    // or an official sheet silently loses every grade the source sheet had.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        var points = new List<SyncPoint>();
        var phaseSeen = new HashSet<string>();
        var prevTime = float.NegativeInfinity;
        foreach (var e in Timeline.Where(e => e.Sync != 0).OrderBy(e => e.Time))
        {
            var isPhaseAnchor = phaseSeen.Add(e.Phase) || (e.Time - prevTime) > 90f;
            points.Add(new SyncPoint { Ability = e.Sync, Time = e.Time, IsPhase = isPhaseAnchor, Label = $"{e.Phase} {e.Mechanic}" });
            prevTime = e.Time;
        }
        return points;
    }

    public static List<BossAnchor> BossAnchors()
    {
        var list = new List<BossAnchor>();
        BossNames.Add(list, "Honey B. Lovely", 10.8f, "Honey B. Lovely");
        return list;
    }
}
