// Generated by the official-fight generator from a FrenMits sheet (M3S - Brute Bomber, territory 1230).
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class M3sData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(12, "P1", "Brutal Impact", 0, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(21, "P1", "Knuckle Sandwich", 0x9423, new[]{"Invulnerability", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(38, "P1", "Octuple Lariat", 0x93D8, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(38, "P1", "Blazing Lariat", 0, new[]{"Party Mit + Reprisal + Rampart + Short Mit", "Party Mit + Rampart", "Temperance + Asylum + Plenary Indulgence", "Neutral Sect + Celestial Opposition + Earthly Star", "", "", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(49, "P1", "Octoboom Dive", 0x93DE, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(53, "P1", "Diveboom", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(61, "P1", "Brutal Impact", 0, new[]{"", "Reprisal", "", "Collective Unconscious", "Whispering Dawn", "Physis II", "", "Feint", "", ""}, 1, false),
        new(77, "P1", "Barbarous Barrage", 0x93FB, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(88, "P1", "Explosion", 0, new[]{"", "", "", "", "Seraphism + Expedient", "Philosophia + Holos", "", "", "", ""}, 1, false),
        new(94, "P1", "Explosion", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(96, "P1", "Murderous Mist", 0x93FE, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(110, "P1", "Doping Draught", 0x9407, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Sacred Soil", "Kerachole + Physis II", "", "", "", ""}, 1, false),
        new(144, "P1", "Quadruple Lariat", 0, new[]{"Party Mit", "Reprisal", "Asylum", "Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole", "Feint", "", "Party Mit", "Addle"}),
        new(144, "P1", "Blazing Lariat", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(155, "P1", "Quadroboom Dive", 0x93E1, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(158, "P1", "Diveboom", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(167, "P1", "Brutal Impact", 0, new[]{"Reprisal", "Party Mit", "Plenary Indulgence", "Earthly Star", "Seraph", "", "", "Feint", "", ""}, 1, false),
        new(178, "P1", "Knuckle Sandwich", 0x9423, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(196, "P1", "Tag Team", 0x93E7, new[]{"", "Reprisal", "Temperance", "Collective Unconscious", "Sacred Soil", "Kerachole + Physis II", "", "", "", ""}),
        new(206, "P1", "Chain Deathmatch", 0x93E5, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(215, "P1", "Lariat Combo", 0x9B34, new[]{"", "", "Liturgy of the Bell", "Macrocosmos + Neutral Sect", "Expedient + Fey Illumination", "Panhaima + Holos", "", "", "", ""}, 1, false),
        new(219, "P1", "Lariat Combo", 0x9B36, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(227, "P1", "Octuple Lariat", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(227, "P1", "Quadruple Lariat", 0x93DA, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(228, "P1", "Blazing Lariat", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(235, "P1", "Brutal Impact", 0, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Sacred Soil + Whispering Dawn", "Kerachole", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(254, "P1", "Final Fusedown", 0x9406, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(267, "P1", "Explosion", 0, new[]{"Party Mit", "Party Mit + Reprisal + Short Mit", "Asylum", "Celestial Opposition + Collective Unconscious", "Sacred Soil", "Physis II + Kerachole", "", "Feint", "", ""}, 2, false),
        new(272, "P1", "Explosion", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(283, "P1", "Diveboom", 0, new[]{"Short Mit", "", "", "", "Seraphism + Seraph", "Philosophia", "", "", "", ""}, 2, false),
        new(299, "P1", "Fusefield", 0x93EE, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Sacred Soil + Whispering Dawn", "Kerachole", "", "", "", ""}),
        new(305, "P1", "Bombarian Flame", 0x93EF, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(310, "P1", "Mana Explosion", 0, new[]{"Short Mit", "Short Mit", "Temperance", "", "", "", "", "", "", ""}, 2, false),
        new(318, "P1", "Mana Explosion", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(322, "P1", "Mana Explosion", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(330, "P1", "Mana Explosion", 0, new[]{"", "Reprisal", "", "Collective Unconscious", "Sacred Soil", "Kerachole + Physis II", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(339, "P1", "Mana Explosion", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(355, "P1", "Knuckle Sandwich", 0x9423, new[]{"Buddy Mit", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(372, "P1", "Doping Draught", 0x9427, new[]{"Reprisal", "Party Mit", "Plenary Indulgence", "Earthly Star", "Sacred Soil + Whispering Dawn", "Kerachole", "", "Feint", "", ""}),
        new(393, "P1", "Bombarian Special", 0x940B, new[]{"Party Mit", "Reprisal", "Asylum", "Neutral Sect + Celestial Opposition", "Expedient + Fey Illumination", "Panhaima + Holos", "", "", "", ""}, 1, false),
        new(398, "P1", "Bombarian Special", 0x940E, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(404, "P1", "Bombarian Special", 0x9411, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(412, "P1", "Bombarian Special", 0x9413, new[]{"Short Mit", "Short Mit", "", "Collective Unconscious", "Seraph + Sacred Soil", "Physis II + Kerachole", "", "", "", ""}, 2, false),
        new(428, "P1", "Fuses of Fury", 0x93FF, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "", "", "Feint", "", "Party Mit", "Addle"}),
        new(434, "P1", "Tag Team", 0x93E7, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(444, "P1", "Chain Deathmatch", 0x93E5, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(459, "P1", "Murderous Mist", 0x9BD7, new[]{"", "Party Mit + Reprisal", "Temperance", "", "Whispering Dawn + Sacred Soil", "Philosophia + Kerachole", "", "Feint", "", ""}, 1, false),
        new(459, "P1", "Lariat Combo", 0x9BED, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(463, "P1", "Lariat Combo", 0x9BEF, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(475, "P1", "Diveboom", 0, new[]{"", "", "", "Collective Unconscious", "Seraphism", "Physis II", "", "", "", ""}, 2, false),
        new(485, "P1", "Brutal Impact", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(498, "P1", "Knuckle Sandwich", 0x9423, new[]{"Buddy Mit", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(518, "P1", "Fuse or Foe", 0x9403, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Sacred Soil", "Kerachole", "Feint", "", "Party Mit", "Addle"}),
        new(527, "P1", "Infernal Spin", 0x941C, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(527, "P1", "Explosive Rain", 0x9416, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(531, "P1", "Explosive Rain", 0x9417, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(535, "P1", "Explosive Rain", 0x9418, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(538, "P1", "Explosion", 0, new[]{"Party Mit + Rampart", "Reprisal + Short Mit", "Liturgy of the Bell + Asylum", "Macrocosmos + Neutral Sect + Celestial Opposition", "Expedient + Seraph + Fey Illumination", "Panhaima + Holos + Physis II", "", "", "", ""}, 2, false),
        new(543, "P1", "Explosive Rain", 0x941B, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(544, "P1", "Explosion", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(549, "P1", "Blazing Lariat", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(556, "P1", "Brutal Impact", 0, new[]{"", "Party Mit", "", "Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole", "", "Feint", "", ""}, 1, false),
    };

    // Phase start times for the practice phase-jump.
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot, by its native label.
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // One action on one second is a single press.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: each phase's first synced cast re-bases the clock.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        var points = new List<SyncPoint>();
        var phaseSeen = new HashSet<string>();
        var prevTime = float.NegativeInfinity;
        foreach (var e in Timeline.Where(e => e.Sync != 0).OrderBy(e => e.Time))
        {
            var isPhaseAnchor = phaseSeen.Add(e.Phase) || (e.Time - prevTime) > 90f;
            points.Add(new SyncPoint { Ability = e.Sync, Time = e.Time, IsPhase = isPhaseAnchor, Label = $"{e.Phase} {e.Mechanic}" });
            prevTime = e.Time;
        }
        return points;
    }

    public static List<BossAnchor> BossAnchors()
    {
        var list = new List<BossAnchor>();
        BossNames.Add(list, "Brute Bomber", 12.1f, "Brute Bomber");
        return list;
    }
}
