// AUTO-GENERATED by the official-fight generator (a dev tool, kept local) from
// an in-game FrenMits sheet
// (M4S - Wicked Thunder, territory 1232). The Actions[] arrays ARE the Auto-planned mit for each column; times
// are seconds from the pull. Review the mit assignments before shipping - they are
// the planner's, not hand-authored. Regenerate by re-running the tool.
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class M4sData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(16, "P1", "Wrath of Zeus", 0x95EF, new[]{"Party Mit + Reprisal + Rampart + Short Mit", "Party Mit + Rampart + Short Mit", "Temperance + Asylum", "Neutral Sect + Celestial Opposition", "Seraphism + Expedient", "Kerachole + Physis II", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(39, "P1", "Bewitching Flight", 0x9671, new[]{"", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Holos", "", "Feint", "", ""}),
        new(50, "P1", "Electrifying Witch Hunt", 0x95E5, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(50, "P1", "Burst", 0x95EA, new[]{"", "", "", "", "Seraph + Fey Illumination", "Philosophia + Kerachole", "", "", "", ""}, 1, false),
        new(58, "P1", "Witch Hunt", 0x95DE, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(58, "P1", "Burst", 0x95EA, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(59, "P1", "Forked Lightning", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(75, "P1", "Widening Witch Hunt", 0x95E0, new[]{"", "", "", "", "Sacred Soil", "Panhaima", "", "", "", ""}),
        new(77, "P1", "Lightning Vortex", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(77, "P1", "Witch Hunt", 0, new[]{"Reprisal", "", "", "", "", "Physis II", "", "", "", ""}, 1, false),
        new(79, "P1", "Thundering", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(82, "P1", "Lightning Vortex", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(84, "P1", "Witch Hunt", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(86, "P1", "Thundering", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(100, "P1", "Wrath of Zeus", 0x95EF, new[]{"Short Mit", "Reprisal + Short Mit", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Whispering Dawn", "Kerachole", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(111, "P1", "Electrope Edge", 0x95C5, new[]{"Rampart", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(119, "P1", "Witchgleam", 0x95C6, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(126, "P1", "Symphony Fantastique", 0x95C8, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(136, "P1", "Sidewise Spark", 0, new[]{"Party Mit", "", "Asylum", "Neutral Sect", "Sacred Soil", "Kerachole", "", "Feint", "", ""}),
        new(137, "P1", "Four Star", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(137, "P1", "Eight Star", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(145, "P1", "Wicked Jolt", 0x95F0, new[]{"Invulnerability", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(159, "P1", "Electrope Edge", 0x95C5, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(164, "P1", "Sidewise Spark", 0, new[]{"Short Mit", "Party Mit + Reprisal + Rampart", "Temperance + Plenary Indulgence", "Celestial Opposition + Earthly Star + Collective Unconscious", "Expedient + Whispering Dawn + Sacred Soil", "Holos + Physis II + Kerachole", "", "", "", ""}, 2, false),
        new(166, "P1", "Witchgleam", 0x9785, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(175, "P1", "Lightning Cage", 0x95CE, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(182, "P1", "Spark III", 0, new[]{"Reprisal", "", "", "", "Seraph", "", "", "", "", ""}, 1, false),
        new(183, "P1", "Lightning Cage", 0x95CF, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(202, "P1", "Spark III", 0, new[]{"", "", "", "", "Seraphism + Fey Illumination", "Kerachole", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(203, "P1", "Lightning Cage", 0x95CF, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(209, "P1", "Wicked Bolt", 0x92C2, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(221, "P1", "Ion Cluster", 0x95D4, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(233, "P1", "ライトロール", 0, new[]{"Party Mit", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "", "Feint", "", ""}),
        new(235, "P1", "Stampeding Thunder", 0, new[]{"", "", "Asylum", "", "", "Philosophia", "", "", "", ""}, 1, false),
        new(242, "P1", "Stampeding Thunder", 0x8E2F, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(253, "P1", "Positron Stream", 0x95D8, new[]{"Reprisal", "", "", "Macrocosmos", "", "Panhaima", "", "", "", ""}),
        new(253, "P1", "Negatron Stream", 0x95D9, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 2, false),
        new(253, "P1", "Electron Stream", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(258, "P1", "Axe Current", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(264, "P1", "Roundhouse Current", 0, new[]{"", "Party Mit", "Liturgy of the Bell", "Neutral Sect", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(264, "P1", "Spinning Current", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(266, "P1", "Electron Stream", 0x95D7, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(266, "P1", "Positron Stream", 0x95D8, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(266, "P1", "Negatron Stream", 0x95D9, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(271, "P1", "Axe Current", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(279, "P1", "Electron Stream", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(279, "P1", "Positron Stream", 0x95D8, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(279, "P1", "Negatron Stream", 0x95D9, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(284, "P1", "Axe Current", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(284, "P1", "Spinning Current", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(292, "P1", "Wicked Jolt", 0x95F0, new[]{"Buddy Mit", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(317, "P1", "Electrope Transplant", 0x98D3, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "Feint", "", "Party Mit", "Addle"}),
        new(325, "P1", "Fulminous Field", 0x90FE, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(331, "P1", "Fulminous Field", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(337, "P1", "Fulminous Field", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(337, "P1", "Conduction Point", 0, new[]{"Party Mit", "Reprisal", "Temperance + Asylum", "Celestial Opposition", "Expedient + Seraph", "Holos", "", "Feint", "", ""}, 1, false),
        new(340, "P1", "Forked Fissures", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(343, "P1", "Fulminous Field", 0, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(351, "P1", "Fulminous Field", 0x90FE, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(357, "P1", "Fulminous Field", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(363, "P1", "Fulminous Field", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(363, "P1", "Conduction Point", 0, new[]{"", "Party Mit", "", "", "Sacred Soil + Fey Illumination", "Kerachole", "", "", "", ""}, 1, false),
        new(366, "P1", "Forked Fissures", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(369, "P1", "Fulminous Field", 0, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(379, "P1", "Soulshock", 0, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Whispering Dawn", "Panhaima + Physis II", "", "", "", ""}, 1, false),
        new(383, "P1", "Impact", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(388, "P1", "Cannonbolt", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(412, "P1", "Cross Tail Switch", 0x95F2, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(422, "P1", "Cross Tail Switch", 0, new[]{"", "Reprisal", "", "Neutral Sect", "Seraphism", "Philosophia", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(430, "P1", "Wicked Blaze", 0x95F7, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(431, "P1", "Sabertail", 0x95F5, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(441, "P1", "Wicked Special", 0x9610, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(457, "P1", "Mustard Bomb", 0x961E, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(458, "P1", "Kindling Cauldron", 0, new[]{"Party Mit + Reprisal + Rampart", "Party Mit + Rampart + Short Mit", "Liturgy of the Bell + Temperance + Asylum", "Macrocosmos + Celestial Opposition + Earthly Star", "", "", "", "Feint", "", ""}, 3, false),
        new(467, "P1", "Mustard Bomb", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(484, "P1", "Switch of Flame", 0x960E, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(484, "P1", "Switch of Tides", 0x960F, new[]{"", "", "Plenary Indulgence", "Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "", "", "", ""}, 1, false),
        new(488, "P1", "Switch of Flame", 0x960E, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(488, "P1", "Switch of Tides", 0x960F, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(505, "P1", "Azure Thunder", 0x962F, new[]{"Short Mit", "Reprisal", "", "", "Expedient + Seraph", "Holos", "", "", "", ""}, 2, false),
        new(512, "P1", "Twilight Sabbath", 0x9623, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(520, "P1", "Wicked Fire", 0x9630, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(523, "P1", "Sidewise Spark", 0x962A, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(524, "P1", "Wicked Fire", 0x9631, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(529, "P1", "Wicked Special", 0x9612, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(530, "P1", "Sidewise Spark", 0x9629, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(541, "P1", "Midnight Sabbath", 0x9AB9, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(552, "P1", "Concentrated Burst", 0x962B, new[]{"", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "Feint", "", "Party Mit", "Addle"}),
        new(552, "P1", "Wicked Cannon", 0x9624, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(552, "P1", "Wicked Flare", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(556, "P1", "Wicked Spark", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(560, "P1", "Wicked Special", 0x9612, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(569, "P1", "Wicked Thunder", 0x949B, new[]{"Reprisal + Party Mit + Rampart + Short Mit", "Party Mit + Rampart", "Asylum", "Neutral Sect", "Fey Illumination", "", "", "Feint", "", ""}, 2, false),
        new(580, "P1", "Aetherial Conversion", 0x9605, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(589, "P1", "Flame Slash", 0x9614, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(594, "P1", "Raining Swords", 0x9616, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(615, "P1", "Chain Lightning", 0x9619, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(621, "P1", "Chain Lightning", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(627, "P1", "Chain Lightning", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(632, "P1", "Chain Lightning", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(658, "P1", "Mustard Bomb", 0x961E, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(658, "P1", "Kindling Cauldron", 0, new[]{"Short Mit", "Reprisal + Short Mit", "Liturgy of the Bell + Temperance + Asylum", "Macrocosmos + Celestial Opposition + Earthly Star", "", "", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(668, "P1", "Mustard Bomb", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(675, "P1", "Aetherial Conversion", 0x9604, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 1, true),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many rows
            // ask for it. Keyed on the ACTION, not the row's cast: two mechanics
            // do land on one second, and a player told to press different things
            // for each is being told to press both.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    // The board's severity marks (! !! !!!) and tank-buster icon come off
    // FightProfile.CustomRows - Hurt/Buster live nowhere else - so a built-in has
    // to hand them over the same way SyncPoints and BossAnchors are handed over,
    // or an official sheet silently loses every grade the source sheet had.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        var points = new List<SyncPoint>();
        var phaseSeen = new HashSet<string>();
        var prevTime = float.NegativeInfinity;
        foreach (var e in Timeline.Where(e => e.Sync != 0).OrderBy(e => e.Time))
        {
            var isPhaseAnchor = phaseSeen.Add(e.Phase) || (e.Time - prevTime) > 90f;
            points.Add(new SyncPoint { Ability = e.Sync, Time = e.Time, IsPhase = isPhaseAnchor, Label = $"{e.Phase} {e.Mechanic}" });
            prevTime = e.Time;
        }
        return points;
    }

    public static List<BossAnchor> BossAnchors()
    {
        var list = new List<BossAnchor>();
        BossNames.Add(list, "Wicked Thunder", 16.1f, "Wicked Thunder");
        return list;
    }
}
