// AUTO-GENERATED by the official-fight generator (a dev tool, kept local) from
// an in-game FrenMits sheet (M5S - Dancing Green, territory 1257).
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class M5sData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(15, "P1", "Deep Cut", 0, new[]{"Invulnerability", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(28, "P1", "Flip to A-Side", 0, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 1, true),
        new(39, "P1", "Play A-Side", 0, new[]{"Party Mit + Reprisal + Rampart + Short Mit", "Party Mit", "Temperance + Asylum + Plenary Indulgence", "Neutral Sect + Celestial Opposition + Earthly Star", "Seraphism + Expedient + Seraph", "Philosophia + Holos + Physis II", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(47, "P1", "Flip to B-Side", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(55, "P1", "3-Snap Twist & Drop the Needle", 0, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(56, "P1", "2-Snap Twist & Drop the Needle", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(58, "P1", "Play B-Side", 0, new[]{"", "Reprisal + Short Mit", "", "Collective Unconscious", "Fey Illumination + Whispering Dawn", "", "", "Feint", "", ""}, 2, false),
        new(65, "P1", "Celebrate Good Times", 0xA723, new[]{"Short Mit", "", "Liturgy of the Bell", "Macrocosmos", "", "Panhaima", "", "", "", ""}, 3, false),
        new(78, "P1", "Disco Infernal", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(82, "P1", "Funky Floor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(87, "P1", "Funky Floor", 0, new[]{"", "Short Mit", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 2, false),
        new(91, "P1", "Funky Floor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(91, "P1", "Inside Out", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(91, "P1", "Outside In", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(95, "P1", "Funky Floor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(99, "P1", "Funky Floor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(100, "P1", "Flip to A-Side", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(100, "P1", "Flip to B-Side", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(103, "P1", "Funky Floor", 0, new[]{"Reprisal + Short Mit", "", "Plenary Indulgence", "Earthly Star", "", "Physis II", "", "", "", ""}, 2, false),
        new(107, "P1", "Funky Floor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(111, "P1", "Funky Floor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(115, "P1", "Funky Floor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(118, "P1", "4-Snap Twist & Drop the Needle", 0, new[]{"", "Reprisal", "", "Collective Unconscious", "Whispering Dawn + Sacred Soil", "Kerachole", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(119, "P1", "2-Snap Twist & Drop the Needle", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(119, "P1", "Funky Floor", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(122, "P1", "Play A-Side", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(122, "P1", "Play B-Side", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(129, "P1", "Celebrate Good Times", 0xA723, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(136, "P1", "Deep Cut", 0, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(148, "P1", "Ensemble Assemble", 0x9A32, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 1, true),
        new(156, "P1", "Arcady Night Fever", 0xA760, new[]{"Party Mit", "", "Asylum", "", "Sacred Soil", "Kerachole", "", "Feint", "", ""}),
        new(156, "P1", "Get Down!", 0x9BE4, new[]{"", "Party Mit", "", "", "", "", "", "", "", ""}, 2, false),
        new(161, "P1", "Get Down!", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(166, "P1", "Get Down!", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(171, "P1", "Get Down!", 0, new[]{"Reprisal + Short Mit", "Short Mit", "Temperance + Plenary Indulgence", "Neutral Sect + Celestial Opposition + Earthly Star", "Expedient + Seraph", "Holos + Physis II", "", "", "", ""}, 2, false),
        new(175, "P1", "Fire", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(183, "P1", "Let's Dance!", 0xA76A, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(187, "P1", "Minor Freak Out", 0, new[]{"", "Reprisal", "", "Collective Unconscious", "Whispering Dawn + Sacred Soil", "Panhaima + Kerachole", "", "", "", ""}, 1, false),
        new(191, "P1", "Let's Dance!", 0, new[]{"", "", "", "", "Fey Illumination", "", "", "", "", ""}, 2, false),
        new(192, "P1", "Minor Freak Out", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(196, "P1", "Let's Dance!", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(197, "P1", "Minor Freak Out", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(202, "P1", "Minor Freak Out", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(210, "P1", "Let's Pose!", 0xA76F, new[]{"Short Mit", "Short Mit", "", "", "", "", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(228, "P1", "Flip to B-Side", 0, new[]{"Rampart", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(234, "P1", "Ride the Waves", 0xA754, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(238, "P1", "Ride the Waves", 0, new[]{"Party Mit + Reprisal + Short Mit", "Short Mit", "Asylum + Plenary Indulgence", "Earthly Star", "Seraphism + Sacred Soil", "Philosophia + Physis II + Kerachole", "", "", "", ""}, 2, false),
        new(244, "P1", "Quarter Beats", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(251, "P1", "Eighth Beats", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(277, "P1", "Play B-Side", 0, new[]{"", "Party Mit + Reprisal", "", "Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole", "", "Feint", "", ""}, 2, false),
        new(285, "P1", "Deep Cut", 0, new[]{"Buddy Mit", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(292, "P1", "Celebrate Good Times", 0xA723, new[]{"", "Rampart + Short Mit", "Liturgy of the Bell + Temperance", "Macrocosmos + Neutral Sect + Celestial Opposition", "Expedient + Seraph", "Holos", "", "", "", ""}, 3, false),
        new(303, "P1", "Frogtourage", 0xA75F, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(317, "P1", "Quarter Beats", 0, new[]{"Reprisal + Short Mit", "Short Mit", "Plenary Indulgence", "Earthly Star", "Fey Illumination + Sacred Soil", "Physis II + Kerachole", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(318, "P1", "Moonburn", 0xA773, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(325, "P1", "Disco Infernal", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(337, "P1", "Back-Up Dance", 0, new[]{"Party Mit + Rampart", "Reprisal", "Asylum", "Collective Unconscious", "Whispering Dawn", "", "", "", "", ""}, 2, false),
        new(347, "P1", "Back-Up Dance", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(354, "P1", "3-Snap Twist & Drop the Needle", 0, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(365, "P1", "Celebrate Good Times", 0xA723, new[]{"Short Mit", "Short Mit", "", "", "", "Panhaima", "", "Feint", "", ""}, 3, false),
        new(377, "P1", "Ensemble Assemble", 0x9A32, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(384, "P1", "Arcady Night Encore", 0xA370, new[]{"Reprisal", "Party Mit", "Plenary Indulgence", "Earthly Star", "Sacred Soil", "Kerachole + Physis II", "", "", "", ""}),
        new(385, "P1", "Get Down!", 0x9BE4, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(390, "P1", "Get Down!", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(395, "P1", "Get Down!", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(400, "P1", "Get Down!", 0, new[]{"Short Mit", "Reprisal + Rampart + Short Mit", "", "Collective Unconscious", "Whispering Dawn", "", "", "", "", ""}, 2, false),
        new(404, "P1", "Fire", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(412, "P1", "Let's Dance! Remix", 0xA390, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(420, "P1", "Let's Dance! Remix", 0, new[]{"", "", "Temperance", "Neutral Sect + Celestial Opposition", "Seraphism + Expedient", "Philosophia + Holos", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(431, "P1", "Let's Pose!", 0xA770, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(450, "P1", "Frogtourage", 0xA75F, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(466, "P1", "Do the Hustle", 0xA725, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(482, "P1", "Moonburn", 0xA773, new[]{"Party Mit + Reprisal + Rampart + Short Mit", "Party Mit", "Liturgy of the Bell + Asylum + Plenary Indulgence", "Macrocosmos + Earthly Star + Collective Unconscious", "Seraph + Fey Illumination + Whispering Dawn", "Panhaima + Physis II + Kerachole", "", "Feint", "", ""}, 2, false),
        new(482, "P1", "Back-Up Dance", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(498, "P1", "Moonburn", 0xA773, new[]{"", "Reprisal + Rampart + Short Mit", "", "", "Sacred Soil", "", "", "", "", ""}, 2, false),
        new(499, "P1", "Back-Up Dance", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many
            // rows ask for it.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        var points = new List<SyncPoint>();
        var phaseSeen = new HashSet<string>();
        var prevTime = float.NegativeInfinity;
        foreach (var e in Timeline.Where(e => e.Sync != 0).OrderBy(e => e.Time))
        {
            var isPhaseAnchor = phaseSeen.Add(e.Phase) || (e.Time - prevTime) > 90f;
            points.Add(new SyncPoint { Ability = e.Sync, Time = e.Time, IsPhase = isPhaseAnchor, Label = $"{e.Phase} {e.Mechanic}" });
            prevTime = e.Time;
        }
        return points;
    }

    public static List<BossAnchor> BossAnchors()
    {
        var list = new List<BossAnchor>();
        BossNames.Add(list, "Dancing Green", 15f, "Dancing Green");
        return list;
    }
}
