// AUTO-GENERATED by the official-fight generator (a dev tool, kept local) from
// an in-game FrenMits sheet (M6S - Sugar Riot, territory 1259).
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class M6sData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(12, "P1", "Mousse Mural", 0xA6BC, new[]{"Party Mit + Reprisal", "Party Mit", "Liturgy of the Bell + Temperance + Asylum", "Macrocosmos + Neutral Sect + Celestial Opposition", "Seraphism + Expedient + Seraph", "Panhaima + Philosophia + Holos", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(23, "P1", "Color Riot", 0xA691, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(25, "P1", "Cool Bomb", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(25, "P1", "Warm Bomb", 0, new[]{"Invulnerability", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(36, "P1", "Wingmark", 0xA676, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 1, true),
        new(71, "P1", "Sticky Mousse", 0xA695, new[]{"", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Fey Illumination + Whispering Dawn + Sacred Soil", "Physis II + Kerachole", "", "Feint", "", ""}, 2, false),
        new(78, "P1", "Burst", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(82, "P1", "Color Riot", 0xA692, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(85, "P1", "Cool Bomb", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(85, "P1", "Warm Bomb", 0, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(92, "P1", "Sugarscape", 0xA668, new[]{"Reprisal", "", "", "", "", "", "", "", "", ""}),
        new(109, "P1", "Layer", 0xA66A, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(123, "P1", "Spray Pain", 0xA6A1, new[]{"Party Mit + Short Mit", "Party Mit + Short Mit", "Asylum", "", "", "", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(129, "P1", "Spray Pain", 0xA6A1, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(135, "P1", "Spray Pain", 0xA6A1, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(142, "P1", "Crowd Brûlée", 0, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(142, "P1", "Brûlée", 0, new[]{"", "Reprisal", "Temperance + Plenary Indulgence", "Neutral Sect + Celestial Opposition + Earthly Star", "", "", "", "", "", ""}, 2, false),
        new(150, "P1", "Sticky Mousse", 0xA695, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(157, "P1", "Burst", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(158, "P1", "Layer", 0xA66C, new[]{"Reprisal", "", "", "Collective Unconscious", "Expedient + Seraph", "Holos + Physis II", "", "", "", ""}, 1, false),
        new(174, "P1", "Brûlée", 0, new[]{"Short Mit", "Short Mit", "", "", "Whispering Dawn + Sacred Soil", "Panhaima + Kerachole", "", "Feint", "", ""}, 2, false),
        new(174, "P1", "Spray Pain", 0x9A2C, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(178, "P1", "Pudding Graf", 0xA6B5, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(190, "P1", "Double Style", 0xA683, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(191, "P1", "Pudding Graf", 0xA6B6, new[]{"", "", "", "", "Fey Illumination", "", "", "", "", ""}, 2, false),
        new(200, "P1", "Mousse Mural", 0xA6BC, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(208, "P1", "Color Riot", 0xA691, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(211, "P1", "Cool Bomb", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(211, "P1", "Warm Bomb", 0, new[]{"Buddy Mit", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(219, "P1", "Soul Sugar", 0xA6A5, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(226, "P1", "Live Painting", 0xA6A6, new[]{"Rampart", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(229, "P1", "Unlimited Craving", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(242, "P1", "I Crave Violence", 0xA6B1, new[]{"Party Mit + Reprisal + Short Mit", "Party Mit + Rampart + Short Mit", "Liturgy of the Bell + Asylum + Plenary Indulgence", "Macrocosmos + Earthly Star + Collective Unconscious", "Seraphism + Whispering Dawn + Sacred Soil", "Philosophia + Physis II + Kerachole", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(255, "P1", "Live Painting", 0xA6A7, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(257, "P1", "I Crave Violence", 0xA6B1, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(266, "P1", "Water III", 0x93C7, new[]{"", "Reprisal", "Temperance", "Neutral Sect + Celestial Opposition", "", "", "", "Feint", "", ""}, 1, false),
        new(276, "P1", "Water III", 0x93C7, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(277, "P1", "Live Painting", 0xA6A8, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(280, "P1", "Unlimited Craving", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(285, "P1", "Manxome Windersnatch", 0, new[]{"", "Short Mit", "", "", "Sacred Soil + Expedient", "Kerachole + Holos", "", "", "", ""}, 2, false),
        new(294, "P1", "I Crave Violence", 0xA6B1, new[]{"", "", "", "", "Seraph", "Panhaima", "", "", "", ""}, 3, false),
        new(307, "P1", "Ready Ore Not", 0xA6AA, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(309, "P1", "I Crave Violence", 0xA6B1, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(316, "P1", "Live Painting", 0xA6A9, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(320, "P1", "Unlimited Craving", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(325, "P1", "Manxome Windersnatch", 0, new[]{"Reprisal + Rampart + Short Mit", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Fey Illumination + Whispering Dawn + Sacred Soil", "Physis II + Kerachole", "", "", "", ""}, 2, false),
        new(328, "P1", "Water III", 0x93C7, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(334, "P1", "I Crave Violence", 0xA6B1, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(337, "P1", "Water III", 0x93C7, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(346, "P1", "Water III", 0x93C7, new[]{"Party Mit", "Party Mit + Reprisal", "Asylum", "", "", "", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(348, "P1", "I Crave Violence", 0xA6B1, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 3, false),
        new(356, "P1", "Water III", 0x93C7, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(365, "P1", "Water III", 0x93C7, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(391, "P1", "Ready Ore Not", 0xA6AA, new[]{"Reprisal", "", "Temperance + Plenary Indulgence", "Neutral Sect + Celestial Opposition + Earthly Star", "Whispering Dawn + Sacred Soil", "Physis II + Kerachole", "", "Feint", "", ""}, 3, false),
        new(400, "P1", "Single Style", 0x9A3D, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(415, "P1", "Cool Bomb", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(415, "P1", "Warm Bomb", 0, new[]{"", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(421, "P1", "Mousse Mural", 0xA6BC, new[]{"Rampart", "Reprisal", "", "Collective Unconscious", "Expedient + Seraph + Sacred Soil", "Panhaima + Holos + Kerachole", "", "", "", ""}, 3, false),
        new(431, "P1", "Sugarscape", 0xA663, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(457, "P1", "Layer", 0xA698, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(469, "P1", "Taste of Thunder", 0xA69D, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1),
        new(476, "P1", "Lightning Bolt", 0xA69A, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(482, "P1", "Lightning Storm", 0, new[]{"Party Mit + Reprisal", "Party Mit + Short Mit", "Liturgy of the Bell + Asylum + Plenary Indulgence", "Macrocosmos + Earthly Star + Collective Unconscious", "Seraphism + Fey Illumination + Whispering Dawn", "Philosophia + Physis II + Kerachole", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(482, "P1", "Levin Drop", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(486, "P1", "Lightning Bolt", 0xA69A, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(492, "P1", "Lightning Storm", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(493, "P1", "Levin Drop", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(497, "P1", "Lightning Bolt", 0xA69A, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(503, "P1", "Lightning Storm", 0, new[]{"", "Reprisal", "", "", "Sacred Soil", "", "", "Feint", "", ""}, 3, false),
        new(504, "P1", "Levin Drop", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(508, "P1", "Lightning Bolt", 0xA69A, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(513, "P1", "Lightning Storm", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(514, "P1", "Levin Drop", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(518, "P1", "Pudding Party", 0xA66D, new[]{"Rampart", "Rampart", "Temperance", "Neutral Sect + Celestial Opposition", "", "Kerachole", "", "", "", ""}, 2, false),
        new(533, "P1", "Layer", 0xA699, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(549, "P1", "Mousse Drip", 0xA6B7, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1),
        new(554, "P1", "Mousse Drip", 0, new[]{"Reprisal", "Short Mit", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Expedient + Seraph + Whispering Dawn", "Panhaima + Holos + Physis II", "", "", "", ""}, 3, false),
        new(559, "P1", "Moussacre", 0xA6BA, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(566, "P1", "Taste of Thunder", 0xA69D, new[]{"", "", "", "", "", "", "", "", "", ""}, 1),
        new(568, "P1", "Explosion", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(572, "P1", "Wingmark", 0xA676, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many
            // rows ask for it.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        var points = new List<SyncPoint>();
        var phaseSeen = new HashSet<string>();
        var prevTime = float.NegativeInfinity;
        foreach (var e in Timeline.Where(e => e.Sync != 0).OrderBy(e => e.Time))
        {
            var isPhaseAnchor = phaseSeen.Add(e.Phase) || (e.Time - prevTime) > 90f;
            points.Add(new SyncPoint { Ability = e.Sync, Time = e.Time, IsPhase = isPhaseAnchor, Label = $"{e.Phase} {e.Mechanic}" });
            prevTime = e.Time;
        }
        return points;
    }

    public static List<BossAnchor> BossAnchors()
    {
        var list = new List<BossAnchor>();
        BossNames.Add(list, "Sugar Riot", 12.3f, "Sugar Riot");
        return list;
    }
}
