// AUTO-GENERATED by the official-fight generator (a dev tool, kept local) from
// an in-game FrenMits sheet (M7S - Brute Abombinator, territory 1261).
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class M7sData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(11, "P1", "Brutal Impact", 0xA55B, new[]{"Reprisal", "Party Mit", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(24, "P1", "Stoneringer", 0xA55E, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(33, "P1", "Smash Here", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(33, "P1", "Brutish Swing", 0, new[]{"", "Reprisal", "Temperance + Asylum", "Neutral Sect + Celestial Opposition", "Seraphism + Expedient", "Holos + Philosophia", "", "Feint", "", ""}, 1, false),
        new(35, "P1", "Brutal Smash", 0, new[]{"", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(44, "P1", "Spore Sac", 0xA569, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(49, "P1", "Spore Sac", 0xA56A, new[]{"Party Mit", "", "Liturgy of the Bell", "", "Seraph + Fey Illumination", "Kerachole", "", "", "", ""}, 1, false),
        new(53, "P1", "Sinister Seeds", 0xA56D, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(55, "P1", "Pollen", 0xA56B, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(58, "P1", "Sinister Seeds", 0xA571, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(62, "P1", "Sinister Seeds", 0xA56E, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(65, "P1", "Impact", 0, new[]{"", "", "Plenary Indulgence", "", "Sacred Soil", "", "", "", "", ""}),
        new(66, "P1", "Tendrils of Terror", 0xA56F, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(72, "P1", "Roots of Evil", 0xA572, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(76, "P1", "Brutish Swing", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(78, "P1", "Brutal Smash", 0, new[]{"", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(79, "P1", "Crossing Crosswinds", 0xA90E, new[]{"Reprisal", "", "", "Earthly Star + Collective Unconscious", "Whispering Dawn", "Kerachole + Physis II", "", "", "", ""}, 1, false),
        new(94, "P1", "Quarry Swamp", 0xA575, new[]{"", "Reprisal", "", "", "Sacred Soil", "", "", "", "", ""}, 1, false),
        new(106, "P1", "Explosion", 0xA576, new[]{"Rampart + Short Mit", "Party Mit + Short Mit", "", "Macrocosmos", "", "Panhaima", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(109, "P1", "Stoneringer", 0xA55D, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(111, "P1", "Explosion", 0xA576, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(118, "P1", "Smash There", 0xA560, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(119, "P1", "Smash Here", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(126, "P1", "Pulp Smash", 0xA577, new[]{"", "", "Asylum + Plenary Indulgence", "", "Sacred Soil", "Kerachole", "", "Feint", "", ""}, 1, false),
        new(130, "P1", "It Came from the Dirt", 0xA57A, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(130, "P1", "The Unpotted", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(149, "P1", "Neo Bombarian Special", 0xA57C, new[]{"Reprisal + Party Mit + Short Mit", "Short Mit", "", "Earthly Star + Collective Unconscious", "Whispering Dawn", "Physis II", "", "", "", ""}, 2, false),
        new(159, "P1", "Grappling Ivy", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(172, "P1", "Stoneringer", 0, new[]{"", "Reprisal", "Temperance", "Neutral Sect + Celestial Opposition", "Sacred Soil + Expedient", "Kerachole + Holos", "", "", "", ""}, 1, false),
        new(181, "P1", "Brutish Swing", 0xA58D, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(186, "P1", "Brutish Swing", 0xA592, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(189, "P1", "Glower Power", 0xA585, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(190, "P1", "Electrogenetic Force", 0, new[]{"", "Rampart + Short Mit", "Plenary Indulgence", "", "Seraph + Fey Illumination", "", "", "", "", ""}, 2, false),
        new(196, "P1", "Revenge of the Vines", 0xA587, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(207, "P1", "Thorny Deathmatch", 0xA588, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(222, "P1", "Abominable Blink", 0xA589, new[]{"Reprisal + Short Mit", "Party Mit + Short Mit", "Asylum", "Earthly Star + Collective Unconscious", "Seraphism + Whispering Dawn + Sacred Soil", "Philosophia + Physis II + Kerachole", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(232, "P1", "Sporesplosion", 0xA58A, new[]{"Rampart", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(238, "P1", "Sporesplosion", 0xA58B, new[]{"", "Reprisal", "", "", "", "", "", "Feint", "", ""}, 1, false),
        new(244, "P1", "Brutish Swing", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(251, "P1", "Glower Power", 0xA585, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(252, "P1", "Electrogenetic Force", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(258, "P1", "Revenge of the Vines", 0xA587, new[]{"Party Mit + Short Mit", "Short Mit", "Plenary Indulgence", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 2, false),
        new(267, "P1", "Demolition Deathmatch", 0xA596, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(281, "P1", "Abominable Blink", 0xA589, new[]{"", "", "Liturgy of the Bell", "", "", "Panhaima", "", "", "", ""}, 3, false),
        new(289, "P1", "Strange Seeds", 0xA597, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(292, "P1", "Brutish Swing", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(294, "P1", "Brutal Smash", 0, new[]{"Buddy Mit", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(295, "P1", "Strange Seeds", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(296, "P1", "Stoneringer", 0xA57F, new[]{"Reprisal", "", "Temperance", "Macrocosmos + Neutral Sect", "Expedient + Whispering Dawn", "Holos + Physis II", "", "", "", ""}, 1, false),
        new(300, "P1", "Tendrils of Terror", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(300, "P1", "Strange Seeds", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(305, "P1", "Tendrils of Terror", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(305, "P1", "Strange Seeds", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(310, "P1", "Tendrils of Terror", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(310, "P1", "Strange Seeds", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(315, "P1", "Tendrils of Terror", 0, new[]{"", "Party Mit + Reprisal", "Asylum + Plenary Indulgence", "Celestial Opposition + Earthly Star", "Seraph + Fey Illumination", "Kerachole", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(320, "P1", "Killer Seeds", 0xA59B, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(325, "P1", "Tendrils of Terror", 0xA59C, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(326, "P1", "Brutish Swing", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(330, "P1", "Brutish Swing", 0xA592, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(334, "P1", "Glower Power", 0xA585, new[]{"", "", "", "Collective Unconscious", "Sacred Soil", "", "", "Feint", "", ""}),
        new(335, "P1", "Electrogenetic Force", 0, new[]{"Rampart", "Short Mit", "", "", "", "", "", "", "", ""}, 2, false),
        new(341, "P1", "Revenge of the Vines", 0xA587, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(353, "P1", "Powerslam", 0xA59E, new[]{"Party Mit", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 2, false),
        new(382, "P1", "Brutal Impact", 0xA55B, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Whispering Dawn", "Kerachole + Physis II", "", "", "", ""}, 1, false),
        new(397, "P1", "Stoneringer 2: Stoneringers", 0xA5A0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(406, "P1", "Brutish Swing", 0xA5A2, new[]{"", "Party Mit + Reprisal", "Asylum", "Collective Unconscious", "Seraphism + Sacred Soil", "Philosophia", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(411, "P1", "Revenge of the Vines", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(416, "P1", "Lashing Lariat", 0xA5A7, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(421, "P1", "Brutish Swing", 0xA5AB, new[]{"", "", "Temperance", "Neutral Sect", "Expedient", "Holos + Kerachole", "", "Feint", "", ""}, 1, false),
        new(427, "P1", "Glower Power", 0xA94A, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(428, "P1", "Electrogenetic Force", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(433, "P1", "Slaminator", 0xA5AD, new[]{"Invulnerability", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(443, "P1", "Brutal Impact", 0xA55B, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Sacred Soil + Whispering Dawn", "Physis II", "", "", "", ""}, 1, false),
        new(455, "P1", "Stoneringer", 0xA55E, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(478, "P1", "Debris Deathmatch", 0xA5B0, new[]{"Party Mit", "Reprisal", "", "Collective Unconscious", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(483, "P1", "Spore Sac", 0xA569, new[]{"", "", "", "Celestial Opposition", "Seraph + Fey Illumination", "", "", "", "", ""}, 1, false),
        new(488, "P1", "Spore Sac", 0xA56A, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(494, "P1", "Pollen", 0xA56B, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(497, "P1", "Killer Seeds", 0xA59B, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(502, "P1", "Tendrils of Terror", 0xA59C, new[]{"", "Party Mit", "Asylum", "", "", "Kerachole", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(514, "P1", "Quarry Swamp", 0xA575, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Whispering Dawn + Sacred Soil", "Physis II", "", "Feint", "", ""}, 1, false),
        new(526, "P1", "Sinister Seeds", 0xA56D, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(530, "P1", "Sinister Seeds", 0xA571, new[]{"", "Reprisal", "Liturgy of the Bell", "Collective Unconscious", "", "", "", "", "", ""}, 1, false),
        new(534, "P1", "Sinister Seeds", 0xA56E, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(540, "P1", "Tendrils of Terror", 0xA56F, new[]{"Short Mit", "Short Mit", "", "Macrocosmos", "", "Panhaima + Kerachole", "", "", "", ""}, 2, false),
        new(540, "P1", "Roots of Evil", 0xA572, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(542, "P1", "Pulp Smash", 0xA577, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(546, "P1", "It Came from the Dirt", 0xA57A, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(546, "P1", "The Unpotted", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(552, "P1", "Brutal Impact", 0xA55B, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(582, "P1", "Strange Seeds", 0xA90A, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "", "", "", ""}),
        new(588, "P1", "Strange Seeds", 0, new[]{"Party Mit", "Party Mit", "Temperance + Asylum", "Neutral Sect", "Seraphism + Expedient", "Philosophia + Holos", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(589, "P1", "Brutish Swing", 0xA5A2, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(593, "P1", "Tendrils of Terror", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(600, "P1", "Brutish Swing", 0xA5A3, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(602, "P1", "Strange Seeds", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(608, "P1", "Tendrils of Terror", 0, new[]{"", "", "", "Collective Unconscious", "Seraph", "", "", "Feint", "", ""}, 1, false),
        new(613, "P1", "Slaminator", 0xA5AD, new[]{"Rampart + Short Mit", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(619, "P1", "Stoneringer", 0xA55D, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many
            // rows ask for it.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        var points = new List<SyncPoint>();
        var phaseSeen = new HashSet<string>();
        var prevTime = float.NegativeInfinity;
        foreach (var e in Timeline.Where(e => e.Sync != 0).OrderBy(e => e.Time))
        {
            var isPhaseAnchor = phaseSeen.Add(e.Phase) || (e.Time - prevTime) > 90f;
            points.Add(new SyncPoint { Ability = e.Sync, Time = e.Time, IsPhase = isPhaseAnchor, Label = $"{e.Phase} {e.Mechanic}" });
            prevTime = e.Time;
        }
        return points;
    }

    public static List<BossAnchor> BossAnchors()
    {
        var list = new List<BossAnchor>();
        BossNames.Add(list, "Brute Abombinator", 10.8f, "Brute Abombinator");
        return list;
    }
}
