// Generated by the official-fight generator from a FrenMits sheet (M8S - Howling Blade, territory 1263).
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class M8sData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(13, "P1", "Extraplanar Pursuit", 0xA3DA, new[]{"Party Mit + Reprisal + Rampart + Short Mit", "Party Mit + Rampart + Short Mit", "Temperance + Asylum", "Earthly Star + Collective Unconscious", "Sacred Soil + Seraphism", "Kerachole + Philosophia", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(30, "P1", "Stonefang", 0xA3A2, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(40, "P1", "Revolutionary Reign", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(42, "P1", "Wolves' Reign", 0xA92C, new[]{"Short Mit", "Reprisal + Short Mit", "Plenary Indulgence", "Neutral Sect + Celestial Opposition", "Expedient + Seraph + Fey Illumination", "Holos + Physis II", "", "Feint", "", ""}, 2, false),
        new(47, "P1", "Wolves' Reign", 0xA39A, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(48, "P1", "Reign's End", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(48, "P1", "Sovereign Scar", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(52, "P1", "Extraplanar Pursuit", 0xA3DA, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(67, "P1", "Millennial Decay", 0xA3B2, new[]{"Short Mit", "Short Mit", "", "", "Whispering Dawn + Sacred Soil", "Kerachole", "", "", "", ""}, 2, false),
        new(78, "P1", "Aero III", 0xA3B7, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(80, "P1", "Breath of Decay", 0xA3B4, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(80, "P1", "Gust", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(85, "P1", "Gust", 0, new[]{"Reprisal", "", "", "Earthly Star + Collective Unconscious", "", "", "", "", "", ""}, 1, false),
        new(94, "P1", "Aero III", 0xA3B7, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(96, "P1", "Prowling Gale", 0xA3B6, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(96, "P1", "Winds of Decay", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(100, "P1", "Eminent Reign", 0xA911, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(102, "P1", "Tracking Tremors", 0xA3B9, new[]{"", "Reprisal", "Plenary Indulgence", "", "", "", "", "", "", ""}, 1, false),
        new(114, "P1", "Extraplanar Pursuit", 0xA3DA, new[]{"Party Mit", "Party Mit", "Asylum", "", "", "Physis II", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(125, "P1", "Great Divide", 0xA3D8, new[]{"Invulnerability", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(140, "P1", "Terrestrial Titans", 0xA3C4, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(144, "P1", "Titanic Pursuit", 0xA3C7, new[]{"", "", "Temperance", "", "Whispering Dawn", "", "", "Feint", "", ""}, 1, false),
        new(148, "P1", "Bare Fangs", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(154, "P1", "Towerfall", 0xA3C6, new[]{"Reprisal + Rampart + Short Mit", "Rampart + Short Mit", "", "Earthly Star + Collective Unconscious", "", "", "", "", "", ""}, 2, false),
        new(160, "P1", "Revolutionary Reign", 0xA914, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(160, "P1", "Eminent Reign", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(162, "P1", "Wolves' Reign", 0xA92C, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(167, "P1", "Wolves' Reign", 0xA399, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(168, "P1", "Reign's End", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(168, "P1", "Sovereign Scar", 0, new[]{"", "Reprisal", "Liturgy of the Bell + Plenary Indulgence", "Macrocosmos + Neutral Sect + Celestial Opposition", "", "", "", "", "", ""}, 3, false),
        new(180, "P1", "Tactical Pack", 0xA3C8, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(189, "P1", "Howling Havoc", 0xA3DB, new[]{"", "", "", "", "Expedient + Seraph", "Physis II + Holos", "", "", "", ""}, 1, false),
        // Unanchored: that cast lands at 30s and 364s, never here.
        new(196, "P1", "Windfang", 0, new[]{"Party Mit + Short Mit", "Party Mit + Short Mit", "Asylum", "", "Seraphism + Fey Illumination", "Philosophia", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(196, "P1", "Stonefang", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(199, "P1", "Pack Predation", 0xA3CC, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(200, "P1", "Alpha Wind", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(200, "P1", "Stalking Wind", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(200, "P1", "Alpha Stone", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(200, "P1", "Stalking Stone", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(202, "P1", "Sand Surge", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(207, "P1", "Wind Surge", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(214, "P1", "Pack Predation", 0xA3CC, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(214, "P1", "Alpha Wind", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(214, "P1", "Stalking Wind", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(214, "P1", "Alpha Stone", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(214, "P1", "Stalking Stone", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(216, "P1", "Sand Surge", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(221, "P1", "Wind Surge", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(228, "P1", "Pack Predation", 0xA3CC, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(228, "P1", "Alpha Wind", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(228, "P1", "Stalking Wind", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(228, "P1", "Alpha Stone", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(228, "P1", "Stalking Stone", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(230, "P1", "Sand Surge", 0, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Whispering Dawn", "", "", "", "", ""}, 1, false),
        new(233, "P1", "Wind Surge", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(252, "P1", "Ravenous Saber", 0xA749, new[]{"Short Mit", "Reprisal + Short Mit", "", "", "Sacred Soil", "Kerachole + Physis II", "", "Feint", "", ""}, 2, false),
        new(269, "P1", "Bare Fangs", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(274, "P1", "Terrestrial Rage", 0xA3BE, new[]{"", "", "", "", "Sacred Soil", "", "", "", "", ""}),
        new(282, "P1", "Suspended Stone", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(282, "P1", "Heavensearth", 0, new[]{"", "", "Temperance", "", "", "Panhaima", "", "", "", ""}, 1, false),
        new(283, "P1", "Shadowchase", 0xA3BC, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(289, "P1", "Suspended Stone", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(289, "P1", "Heavensearth", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(294, "P1", "Roaring Wind", 0xA78A, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(296, "P1", "Revolutionary Reign", 0xA913, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(300, "P1", "Wolves' Reign", 0xA92C, new[]{"Party Mit + Reprisal", "Party Mit", "Asylum + Plenary Indulgence", "Neutral Sect + Celestial Opposition + Earthly Star", "Whispering Dawn", "Kerachole", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(300, "P1", "Revolutionary Reign", 0xA931, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(305, "P1", "Wolves' Reign", 0xA39A, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(306, "P1", "Reign's End", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(306, "P1", "Sovereign Scar", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(309, "P1", "Weal of Stone", 0xA78E, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(319, "P1", "Great Divide", 0xA3D8, new[]{"Rampart + Short Mit", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(334, "P1", "Beckon Moonlight", 0xA3C1, new[]{"", "Reprisal", "", "Collective Unconscious", "Sacred Soil", "Kerachole + Physis II", "", "Feint", "", ""}),
        new(341, "P1", "Terrestrial Rage", 0xA3BE, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(346, "P1", "Suspended Stone", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(346, "P1", "Heavensearth", 0, new[]{"", "", "", "", "Expedient + Seraph", "Holos", "", "", "", ""}, 1, false),
        new(355, "P1", "Suspended Stone", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(355, "P1", "Heavensearth", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(359, "P1", "Weal of Stone", 0xA792, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(373, "P1", "Tracking Tremors", 0xA3B9, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star", "Sacred Soil + Whispering Dawn", "Kerachole", "", "", "", ""}, 1, false),
        new(444, "P2", "Quake III", 0xA45A, new[]{"Party Mit", "Reprisal + Party Mit", "Plenary Indulgence + Temperance", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Physis II + Kerachole", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(456, "P2", "Ultraviolent Ray", 0xA45C, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(467, "P2", "Twinbite", 0xA4CD, new[]{"Buddy Mit", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(480, "P2", "Hero's Blow", 0xA45F, new[]{"Rampart", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(490, "P2", "Ultraviolent Ray", 0xA45C, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(501, "P2", "Quake III", 0xA45A, new[]{"Reprisal + Short Mit", "Short Mit", "Asylum", "Neutral Sect + Celestial Opposition", "Seraphism + Expedient", "Philosophia + Holos", "", "Feint", "", ""}, 2, false),
        new(513, "P2", "Mooncleaver", 0xA465, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(521, "P2", "Elemental Purge", 0xA467, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(525, "P2", "Hunter's Harvest", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(526, "P2", "Aerotemporal Blast", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(526, "P2", "Geotemporal Blast", 0, new[]{"Short Mit", "Reprisal + Short Mit", "Liturgy of the Bell + Plenary Indulgence", "Macrocosmos + Earthly Star + Collective Unconscious", "Seraph + Fey Illumination + Whispering Dawn", "Panhaima + Physis II", "", "", "", ""}, 3, false),
        new(531, "P2", "Prowling Gale", 0xA46E, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(540, "P2", "Prowling Gale", 0xA46F, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(542, "P2", "Rise of the Howling Wind", 0xA82A, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(552, "P2", "Twofold Tempest", 0xA471, new[]{"Party Mit", "Party Mit", "", "", "Sacred Soil", "Kerachole", "Feint", "", "Party Mit", "Addle"}),
        new(555, "P2", "Wind Surge", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(559, "P2", "Twofold Tempest", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(566, "P2", "Twofold Tempest", 0, new[]{"Reprisal", "", "Temperance", "", "", "", "", "", "", ""}, 1, false),
        new(573, "P2", "Twofold Tempest", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(585, "P2", "Bare Fangs", 0xA475, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        // Unanchored: Hero's Blow lands at 480s and 697s, not here.
        new(589, "P2", "Hero's Blow", 0, new[]{"", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "", "", "", "", "", ""}, 1, false),
        new(596, "P2", "Champion's Circuit", 0xA478, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(600, "P2", "Champion's Circuit", 0, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(605, "P2", "Champion's Circuit", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(609, "P2", "Champion's Circuit", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(613, "P2", "Champion's Circuit", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(624, "P2", "Quake III", 0xA45A, new[]{"", "", "Asylum", "Neutral Sect + Celestial Opposition", "Expedient + Whispering Dawn", "Holos + Physis II", "", "Feint", "", ""}, 2, false),
        new(639, "P2", "Ultraviolent Ray", 0xA45C, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(650, "P2", "Twinbite", 0xA4CD, new[]{"Buddy Mit", "Rampart + Short Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(665, "P2", "Rise of the Hunter's Blade", 0xA82C, new[]{"Rampart", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(670, "P2", "Lone Wolf's Lament", 0xA483, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(680, "P2", "Prowling Gale", 0xA485, new[]{"", "Short Mit", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, true),
        new(689, "P2", "Prowling Gale", 0xA486, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(711, "P2", "Ultraviolent Ray", 0xA45C, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(726, "P2", "Howling Eight", 0xAA02, new[]{"Party Mit + Reprisal", "Party Mit", "Liturgy of the Bell + Temperance", "Macrocosmos + Earthly Star", "Seraphism + Seraph", "Panhaima + Philosophia", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(730, "P2", "Howling Eight", 0xAA07, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(736, "P2", "Mooncleaver", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(745, "P2", "Howling Eight", 0, new[]{"", "Reprisal", "Asylum + Plenary Indulgence", "Neutral Sect + Celestial Opposition + Collective Unconscious", "Expedient + Fey Illumination + Whispering Dawn", "Holos + Physis II + Kerachole", "", "Feint", "", ""}, 3, false),
        new(750, "P2", "Howling Eight", 0xA499, new[]{"Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(756, "P2", "Mooncleaver", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(765, "P2", "Howling Eight", 0, new[]{"", "", "", "", "Sacred Soil", "", "", "", "", ""}, 3, false),
        new(769, "P2", "Howling Eight", 0xA499, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 2, true),
        new(775, "P2", "Mooncleaver", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(782, "P2", "Howling Eight", 0, new[]{"Rampart + Short Mit", "Short Mit", "", "", "", "Kerachole", "", "", "", ""}, 3, false),
    };

    // Phase start times for the practice phase-jump.
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot, by its native label.
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // One action on one second is a single press.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: each phase's first synced cast re-bases the clock.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        var points = new List<SyncPoint>();
        var phaseSeen = new HashSet<string>();
        var prevTime = float.NegativeInfinity;
        foreach (var e in Timeline.Where(e => e.Sync != 0).OrderBy(e => e.Time))
        {
            var isPhaseAnchor = phaseSeen.Add(e.Phase) || (e.Time - prevTime) > 90f;
            points.Add(new SyncPoint { Ability = e.Sync, Time = e.Time, IsPhase = isPhaseAnchor, Label = $"{e.Phase} {e.Mechanic}" });
            prevTime = e.Time;
        }
        return points;
    }

    public static List<BossAnchor> BossAnchors()
    {
        var list = new List<BossAnchor>();
        BossNames.Add(list, "Howling Blade", 12.7f, "Howling Blade");
        return list;
    }
}
