// AUTO-GENERATED by the official-fight generator (a dev tool, kept local) from
// an in-game FrenMits sheet
// (M9S - Vamp Fatale, territory 1321). The Actions[] arrays ARE the Auto-planned mit for each column; times
// are seconds from the pull. Review the mit assignments before shipping - they are
// the planner's, not hand-authored. Regenerate by re-running the tool.
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class M9sData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(11, "P1", "Killer Voice", 0xB384, new[]{"Party Mit + Reprisal", "Party Mit", "Liturgy of the Bell + Temperance + Asylum", "Macrocosmos + Neutral Sect + Earthly Star", "Seraphism + Expedient + Seraph", "Philosophia + Holos + Panhaima", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(19, "P1", "Hardcore", 0xB35A, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(21, "P1", "Hardcore", 0xB37F, new[]{"", "Invulnerability", "", "", "", "", "", "", "", ""}, 3, true),
        new(30, "P1", "Vamp Stomp", 0xB34A, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(34, "P1", "Blast Beat", 0, new[]{"", "Reprisal + Rampart", "Plenary Indulgence", "Collective Unconscious + Celestial Opposition", "Fey Illumination + Whispering Dawn", "Physis II", "", "Feint", "", ""}, 2, false),
        new(37, "P1", "Blast Beat", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(40, "P1", "Blast Beat", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(46, "P1", "Brutal Rain", 0xB35D, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(61, "P1", "Sadistic Screech", 0xB333, new[]{"Short Mit", "Short Mit", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 3, false),
        new(69, "P1", "Dead Wake", 0xB367, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(76, "P1", "Half Moon", 0, new[]{"Reprisal", "", "", "Earthly Star", "", "", "", "", "", ""}),
        new(76, "P1", "Coffinfiller", 0xB706, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(79, "P1", "Half Moon", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(79, "P1", "Coffinfiller", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(86, "P1", "Dead Wake", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(93, "P1", "Half Moon", 0, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(94, "P1", "Coffinfiller", 0xB369, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(97, "P1", "Half Moon", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(97, "P1", "Coffinfiller", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(103, "P1", "Dead Wake", 0xB705, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(110, "P1", "Half Moon", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(111, "P1", "Coffinfiller", 0xB36A, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(114, "P1", "Half Moon", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(114, "P1", "Coffinfiller", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(121, "P1", "Half Moon", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(124, "P1", "Half Moon", 0, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(139, "P1", "Sadistic Screech", 0xB333, new[]{"Party Mit + Reprisal + Short Mit", "Party Mit + Short Mit", "Temperance + Asylum + Plenary Indulgence", "Neutral Sect + Earthly Star + Collective Unconscious", "Expedient + Seraph + Whispering Dawn", "Panhaima + Holos + Physis II", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(148, "P1", "Crowd Kill", 0xB33E, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(154, "P1", "Crowd Kill", 0, new[]{"", "Reprisal", "", "Celestial Opposition", "Fey Illumination + Sacred Soil", "Kerachole", "", "Feint", "", ""}, 3, false),
        new(172, "P1", "Finale Fatale", 0xB340, new[]{"Short Mit", "Short Mit", "", "", "", "", "", "", "", ""}, 3, false),
        new(178, "P1", "Pulping Pulse", 0xB373, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(191, "P1", "Aetherletting", 0xB38F, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(194, "P1", "Aetherletting", 0xB392, new[]{"", "", "", "", "Seraphism", "Philosophia", "", "", "", ""}, 2, false),
        new(198, "P1", "Aetherletting", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(208, "P1", "Aetherletting", 0xB393, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(212, "P1", "Aetherletting", 0, new[]{"Reprisal", "", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Whispering Dawn", "Physis II", "", "", "", ""}),
        new(219, "P1", "Hardcore", 0xB35A, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 2, true),
        new(221, "P1", "Hardcore", 0xB37F, new[]{"Invulnerability", "", "", "", "", "", "", "", "", ""}, 3, true),
        new(226, "P1", "Pulping Pulse", 0xB373, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(231, "P1", "Vamp Stomp", 0xB34A, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(234, "P1", "Blast Beat", 0, new[]{"Party Mit + Short Mit", "Party Mit + Reprisal + Short Mit", "Asylum", "Celestial Opposition", "", "", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(237, "P1", "Blast Beat", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(247, "P1", "Half Moon", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(251, "P1", "Half Moon", 0, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(257, "P1", "Brutal Rain", 0xB35D, new[]{"", "", "", "", "", "", "", "Feint", "", ""}, 2, false),
        new(261, "P1", "Brutal Rain", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(269, "P1", "Insatiable Thirst", 0xB344, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(272, "P1", "Insatiable Thirst", 0, new[]{"Reprisal", "", "Temperance + Plenary Indulgence", "Neutral Sect + Earthly Star", "Expedient + Seraph", "Holos + Physis II", "", "", "", ""}, 2, false),
        new(284, "P1", "Sadistic Screech", 0xB333, new[]{"", "", "Liturgy of the Bell", "Macrocosmos + Collective Unconscious", "Fey Illumination + Whispering Dawn + Sacred Soil", "Panhaima + Kerachole", "", "", "", ""}, 3, false),
        new(289, "P1", "Gravegrazer", 0, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(291, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(294, "P1", "Gravegrazer", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 2, true),
        new(297, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(297, "P1", "Plummet", 0xB38B, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(300, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(302, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(304, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(306, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(306, "P1", "Killer Voice", 0xB384, new[]{"", "Reprisal", "", "Celestial Opposition", "", "", "", "", "", ""}, 3, false),
        new(309, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(312, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(315, "P1", "Gravegrazer", 0, new[]{"Rampart", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(316, "P1", "Plummet", 0xB38B, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(317, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(319, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(321, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(323, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(324, "P1", "Killer Voice", 0xB384, new[]{"Party Mit", "Party Mit", "Asylum", "", "Sacred Soil", "Kerachole", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(326, "P1", "Gravegrazer", 0, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1, true),
        new(329, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(332, "P1", "Gravegrazer", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 2, true),
        new(334, "P1", "Plummet", 0xB38B, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(334, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(336, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(338, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(341, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(345, "P1", "Gravegrazer", 0, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 1, true),
        new(348, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(350, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(352, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(354, "P1", "Gravegrazer", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(357, "P1", "Gravegrazer", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(357, "P1", "Sadistic Screech", 0xB333, new[]{"", "Reprisal + Short Mit", "Plenary Indulgence", "Earthly Star + Collective Unconscious + Celestial Opposition", "Whispering Dawn + Sacred Soil", "Physis II + Kerachole", "", "Feint", "", ""}, 3, false),
        new(367, "P1", "Crowd Kill", 0xB33E, new[]{"Reprisal", "", "", "", "", "", "", "", "", ""}),
        new(372, "P1", "Crowd Kill", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(390, "P1", "Finale Fatale", 0xB341, new[]{"", "", "", "", "Seraphism + Sacred Soil", "Philosophia + Kerachole", "", "", "", ""}, 3, false),
        new(396, "P1", "Pulping Pulse", 0xB373, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(401, "P1", "Hell in a Cell", 0xB395, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(402, "P1", "Bloody Bondage", 0xB396, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(405, "P1", "Blood Lash", 0, new[]{"", "", "Temperance", "Neutral Sect", "Expedient + Seraph", "Holos", "", "", "", ""}, 1, false),
        new(408, "P1", "Blood Lash", 0, new[]{"Buddy Mit", "Short Mit", "", "", "", "", "", "", "", ""}, 2, true),
        new(409, "P1", "Ultrasonic Spread", 0xB39C, new[]{"Rampart", "", "", "", "Fey Illumination", "Panhaima", "", "", "", ""}, 2, false),
        new(411, "P1", "Blood Lash", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(414, "P1", "Blood Lash", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(416, "P1", "Ultrasonic Amp", 0xB39D, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(417, "P1", "Blood Lash", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(423, "P1", "Hell in a Cell", 0xB395, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(424, "P1", "Bloody Bondage", 0xB396, new[]{"Party Mit + Reprisal", "Party Mit", "Asylum + Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(427, "P1", "Blood Lash", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(430, "P1", "Blood Lash", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(432, "P1", "Ultrasonic Amp", 0, new[]{"", "", "", "Celestial Opposition", "", "", "", "", "", ""}, 2, false),
        new(433, "P1", "Blood Lash", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(439, "P1", "Ultrasonic Spread", 0xB39C, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(445, "P1", "Pulping Pulse", 0xB373, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(449, "P1", "Pulping Pulse", 0, new[]{"", "Reprisal", "Liturgy of the Bell", "", "", "", "", "Feint", "", ""}),
        new(454, "P1", "Undead Deathmatch", 0xB3A0, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}, 1, false),
        new(455, "P1", "Bloody Bondage", 0xB3A1, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(461, "P1", "Sanguine Scratch", 0xB3A4, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(480, "P1", "Sanguine Scratch", 0xB3A5, new[]{"", "", "", "Macrocosmos", "", "", "", "", "", ""}),
        new(490, "P1", "Explosion", 0, new[]{"Short Mit", "", "", "", "", "", "", "", "", ""}, 1, true),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many rows
            // ask for it. Keyed on the ACTION, not the row's cast: two mechanics
            // do land on one second, and a player told to press different things
            // for each is being told to press both.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    // The board's severity marks (! !! !!!) and tank-buster icon come off
    // FightProfile.CustomRows - Hurt/Buster live nowhere else - so a built-in has
    // to hand them over the same way SyncPoints and BossAnchors are handed over,
    // or an official sheet silently loses every grade the source sheet had.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        return SyncAnchors.Build(
            Timeline.Select(e => (e.Sync, (float)e.Time, e.Phase, e.Mechanic)));
    }

    public static List<BossAnchor> BossAnchors() => new();
}
