// AUTO-GENERATED by the official-fight generator (a dev tool, kept local) from
// an in-game FrenMits sheet
// (Zelenia, territory 1271). The Actions[] arrays ARE the Auto-planned mit for each column; times
// are seconds from the pull. Review the mit assignments before shipping - they are
// the planner's, not hand-authored. Regenerate by re-running the tool.
using System;
using System.Collections.Generic;
using System.Linq;

namespace FrenMits;

public static class ZeleniaData
{
    public static readonly string[] Slots = { "MT", "OT", "WHM", "AST", "SCH", "SGE", "D1", "D2", "D3", "D4" };

    public sealed record Entry(int Time, string Phase, string Mechanic, uint Sync, string[] Actions,
                              int Hurt = 0, bool Buster = false, bool Enrage = false);

    public static readonly Entry[] Timeline =
    {
        new(12, "P1", "Thorned Catharsis", 0xA89E, new[]{"Party Mit + Reprisal + Short Mit", "Party Mit + Short Mit", "Liturgy of the Bell + Temperance + Asylum", "Macrocosmos + Neutral Sect + Celestial Opposition", "Seraphism + Expedient + Seraph", "Philosophia + Holos + Panhaima", "Feint", "", "Party Mit", "Addle"}, 3, false),
        new(22, "P1", "Shock", 0xA8A1, new[]{"Rampart", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(29, "P1", "Alexandrian Holy", 0xA8C0, new[]{"", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "", "Feint", "", ""}),
        new(31, "P1", "Shock", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(33, "P1", "Explosion", 0xA8DA, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(35, "P1", "Shock", 0, new[]{"", "Rampart", "", "", "", "", "", "", "", ""}, 1, true),
        new(45, "P1", "Specter of the Lost", 0xA89F, new[]{"Invulnerability", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(65, "P1", "Escelons' Fall", 0xA8AD, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(69, "P1", "Escelons' Fall", 0, new[]{"Short Mit", "", "", "", "Fey Illumination", "", "", "", "", ""}, 2, false),
        new(74, "P1", "Escelons' Fall", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(85, "P1", "Stock Break", 0xA8D5, new[]{"Reprisal", "Short Mit", "", "", "", "", "", "", "", ""}, 2, false),
        new(89, "P1", "Stock Break", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(95, "P1", "Blessed Barricade", 0xA8B5, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(107, "P1", "Explosion", 0xA83C, new[]{"Party Mit + Short Mit", "Party Mit + Reprisal", "Asylum + Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Physis II", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(119, "P1", "Explosion", 0xA83C, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(131, "P1", "Explosion", 0xA83C, new[]{"Rampart", "Rampart + Short Mit", "", "", "", "", "", "Feint", "", ""}, 2, false),
        new(139, "P1", "Perfumed Quietus", 0xA8B7, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(146, "P1", "Perfumed Quietus", 0xA8CD, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
        new(160, "P1", "Roseblood Bloom", 0xA8B9, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(161, "P1", "Queen's Crusade", 0xA8BA, new[]{"Reprisal + Short Mit", "Short Mit", "Temperance", "Neutral Sect + Celestial Opposition", "Expedient + Seraph", "Holos", "", "", "", ""}, 2, false),
        new(169, "P1", "Alexandrian Thunder II", 0xA8BE, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(189, "P1", "Alexandrian Thunder III", 0xA8E3, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(197, "P1", "Thorned Catharsis", 0xA89E, new[]{"Short Mit", "Reprisal + Short Mit", "Liturgy of the Bell + Plenary Indulgence", "Macrocosmos + Earthly Star + Collective Unconscious", "Seraphism + Fey Illumination + Whispering Dawn", "Panhaima + Philosophia + Physis II", "", "", "", ""}, 3, false),
        new(207, "P1", "Roseblood: 2nd Bloom", 0xAA14, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(208, "P1", "Queen's Crusade", 0xA8BA, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(216, "P1", "Thunder Slash", 0xA9B9, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(219, "P1", "Alexandrian Thunder IV", 0xA9BB, new[]{"Party Mit", "Party Mit", "Asylum", "", "", "", "Feint", "", "Party Mit", "Addle"}, 2, false),
        new(232, "P1", "Specter of the Lost", 0xA89F, new[]{"Rampart + Short Mit", "Buddy Mit", "", "", "", "", "", "", "", ""}, 3, true),
        new(242, "P1", "Roseblood: 3rd Bloom", 0xAA15, new[]{"", "", "", "", "Sacred Soil", "Kerachole", "", "", "", ""}),
        new(243, "P1", "Queen's Crusade", 0xA8BA, new[]{"Reprisal", "Rampart", "", "", "", "", "", "Feint", "", ""}, 2, false),
        new(248, "P1", "Bud of Valor", 0xA8B2, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(256, "P1", "Emblazon", 0xA8BB, new[]{"", "", "", "", "", "", "", "", "", ""}, 1),
        new(264, "P1", "Emblazon", 0, new[]{"", "Reprisal", "Temperance + Plenary Indulgence", "Earthly Star + Collective Unconscious", "Sacred Soil + Whispering Dawn", "Kerachole + Holos", "", "", "", ""}, 1, false),
        new(268, "P1", "Explosion", 0xA8C1, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, false),
        new(276, "P1", "Thorned Catharsis", 0xA89E, new[]{"Short Mit", "Short Mit", "", "", "", "Physis II", "", "", "", ""}, 3, false),
        new(288, "P1", "Bud of Valor", 0xA8B2, new[]{"", "", "", "", "", "", "", "", "", ""}, 1, true),
        new(304, "P1", "Shock", 0, new[]{"Party Mit + Reprisal", "Party Mit", "Asylum", "Neutral Sect + Celestial Opposition", "Sacred Soil + Expedient", "Kerachole", "Feint", "", "Party Mit", "Addle"}, 1, false),
        new(305, "P1", "Alexandrian Banish II", 0, new[]{"Short Mit", "Short Mit", "", "", "Seraph", "", "", "", "", ""}, 3, false),
        new(310, "P1", "Escelons' Fall", 0xA8AD, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(314, "P1", "Escelons' Fall", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(319, "P1", "Escelons' Fall", 0, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(330, "P1", "Stock Break", 0xA8D5, new[]{"", "Reprisal", "Plenary Indulgence", "Earthly Star + Collective Unconscious", "Fey Illumination + Whispering Dawn", "Panhaima + Physis II + Kerachole", "", "Feint", "", ""}, 2, false),
        new(334, "P1", "Stock Break", 0, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(342, "P1", "Roseblood: 4th Bloom", 0xAA16, new[]{"", "", "", "", "", "", "", "", "", ""}),
        new(343, "P1", "Queen's Crusade", 0xA8BA, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(348, "P1", "Emblazon", 0xA8BB, new[]{"", "Short Mit", "", "", "", "", "", "", "", ""}, 1),
        new(356, "P1", "Emblazon", 0, new[]{"", "", "", "", "Sacred Soil", "", "", "", "", ""}, 1, false),
        new(356, "P1", "Alexandrian Thunder III", 0xA8E4, new[]{"", "", "", "", "", "", "", "", "", ""}, 2, false),
        new(360, "P1", "Encircling Thorns", 0xA8C3, new[]{"Rampart + Short Mit", "", "", "", "", "", "", "", "", ""}, 2, true),
        new(368, "P1", "Alexandrian Banish III", 0xA8E8, new[]{"Reprisal", "Rampart", "", "", "", "Kerachole", "", "", "", ""}, 3, false),
        new(380, "P1", "Thorned Catharsis", 0xA89E, new[]{"", "", "", "", "", "", "", "", "", ""}, 3, false),
    };

    // Phase start times for the practice phase-jump (derived from the Timeline).
    public static List<(string Name, float Time)> PhaseStarts()
        => Timeline.GroupBy(e => e.Phase)
                   .Select(g => (g.Key, g.Min(e => (float)e.Time)))
                   .OrderBy(x => x.Item2).ToList();

    // Build mit lines for a sheet slot (native MT/OT/D1-D4 labels).
    public static List<MitLine> BuildLines(string slot)
    {
        var idx = Array.IndexOf(Slots, slot);
        var list = new List<MitLine>();
        if (idx < 0) return list;
        var seen = new HashSet<(int Time, string Action)>();
        foreach (var e in Timeline)
        {
            var action = e.Actions[idx].Trim();
            if (action.Length == 0) continue;
            // The same button on the same second is one press, however many rows
            // ask for it. Keyed on the ACTION, not the row's cast: two mechanics
            // do land on one second, and a player told to press different things
            // for each is being told to press both.
            if (!seen.Add((e.Time, action))) continue;
            list.Add(new MitLine { Time = e.Time, Mechanic = e.Mechanic, Action = action, Enabled = true });
        }
        return list;
    }

    // Resync anchors: the first synced cast of each phase re-bases the clock
    // (wide window), so a faster/slower kill still snaps into place.
    // The board's severity marks (! !! !!!) and tank-buster icon come off
    // FightProfile.CustomRows - Hurt/Buster live nowhere else - so a built-in has
    // to hand them over the same way SyncPoints and BossAnchors are handed over,
    // or an official sheet silently loses every grade the source sheet had.
    public static List<CustomRow> CustomRows()
    {
        var rows = new List<CustomRow>();
        foreach (var e in Timeline)
            if (e.Hurt > 0 || e.Buster || e.Enrage)
                rows.Add(new CustomRow { Time = e.Time, Mechanic = e.Mechanic, Hurt = e.Hurt,
                                          Buster = e.Buster, Enrage = e.Enrage });
        return rows;
    }

    public static List<SyncPoint> SyncPoints()
    {
        var points = new List<SyncPoint>();
        var phaseSeen = new HashSet<string>();
        var prevTime = float.NegativeInfinity;
        foreach (var e in Timeline.Where(e => e.Sync != 0).OrderBy(e => e.Time))
        {
            var isPhaseAnchor = phaseSeen.Add(e.Phase) || (e.Time - prevTime) > 90f;
            points.Add(new SyncPoint { Ability = e.Sync, Time = e.Time, IsPhase = isPhaseAnchor, Label = $"{e.Phase} {e.Mechanic}" });
            prevTime = e.Time;
        }
        return points;
    }

    public static List<BossAnchor> BossAnchors()
    {
        var list = new List<BossAnchor>();
        BossNames.Add(list, "Zelenia", 12f, "Zelenia");
        return list;
    }
}
